// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface AddressResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddressResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An array of MWEB addresses within the requested range.
   * </pre>
   *
   * <code>repeated string address = 1;</code>
   * @return A list containing the address.
   */
  java.util.List<java.lang.String>
      getAddressList();
  /**
   * <pre>
   * An array of MWEB addresses within the requested range.
   * </pre>
   *
   * <code>repeated string address = 1;</code>
   * @return The count of address.
   */
  int getAddressCount();
  /**
   * <pre>
   * An array of MWEB addresses within the requested range.
   * </pre>
   *
   * <code>repeated string address = 1;</code>
   * @param index The index of the element to return.
   * @return The address at the given index.
   */
  java.lang.String getAddress(int index);
  /**
   * <pre>
   * An array of MWEB addresses within the requested range.
   * </pre>
   *
   * <code>repeated string address = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the address at the given index.
   */
  com.google.protobuf.ByteString
      getAddressBytes(int index);
}
