// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface AddressRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddressRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The starting index of the range.
   * </pre>
   *
   * <code>uint32 from_index = 1;</code>
   * @return The fromIndex.
   */
  int getFromIndex();

  /**
   * <pre>
   * The ending index of the range. The result will contain all
   * addresses up to but not including this index.
   * </pre>
   *
   * <code>uint32 to_index = 2;</code>
   * @return The toIndex.
   */
  int getToIndex();

  /**
   * <pre>
   * The scan secret or view key represents the account for
   * which addresses should be returned.
   * </pre>
   *
   * <code>bytes scan_secret = 3;</code>
   * @return The scanSecret.
   */
  com.google.protobuf.ByteString getScanSecret();

  /**
   * <pre>
   * The public key of the spend secret for the account. The spend
   * key is required for spending utxos but is also required
   * for generating addresses.
   * </pre>
   *
   * <code>bytes spend_pubkey = 4;</code>
   * @return The spendPubkey.
   */
  com.google.protobuf.ByteString getSpendPubkey();
}
