// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code AddressResponse}
 */
@com.google.protobuf.Generated
public final class AddressResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:AddressResponse)
    AddressResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "AddressResponse");
  }
  // Use AddressResponse.newBuilder() to construct.
  private AddressResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AddressResponse() {
    address_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_AddressResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_AddressResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_AddressResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.AddressResponse.class, com.sparrowwallet.sparrow.mweb.proto.AddressResponse.Builder.class);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList address_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * An array of MWEB addresses within the requested range.
   * </pre>
   *
   * <code>repeated string address = 1;</code>
   * @return A list containing the address.
   */
  public com.google.protobuf.ProtocolStringList
      getAddressList() {
    return address_;
  }
  /**
   * <pre>
   * An array of MWEB addresses within the requested range.
   * </pre>
   *
   * <code>repeated string address = 1;</code>
   * @return The count of address.
   */
  public int getAddressCount() {
    return address_.size();
  }
  /**
   * <pre>
   * An array of MWEB addresses within the requested range.
   * </pre>
   *
   * <code>repeated string address = 1;</code>
   * @param index The index of the element to return.
   * @return The address at the given index.
   */
  public java.lang.String getAddress(int index) {
    return address_.get(index);
  }
  /**
   * <pre>
   * An array of MWEB addresses within the requested range.
   * </pre>
   *
   * <code>repeated string address = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the address at the given index.
   */
  public com.google.protobuf.ByteString
      getAddressBytes(int index) {
    return address_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < address_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, address_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < address_.size(); i++) {
        dataSize += computeStringSizeNoTag(address_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAddressList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.AddressResponse)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.AddressResponse other = (com.sparrowwallet.sparrow.mweb.proto.AddressResponse) obj;

    if (!getAddressList()
        .equals(other.getAddressList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAddressCount() > 0) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddressList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.AddressResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AddressResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AddressResponse)
      com.sparrowwallet.sparrow.mweb.proto.AddressResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_AddressResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_AddressResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.AddressResponse.class, com.sparrowwallet.sparrow.mweb.proto.AddressResponse.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.AddressResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      address_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_AddressResponse_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.AddressResponse getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.AddressResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.AddressResponse build() {
      com.sparrowwallet.sparrow.mweb.proto.AddressResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.AddressResponse buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.AddressResponse result = new com.sparrowwallet.sparrow.mweb.proto.AddressResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.AddressResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        address_.makeImmutable();
        result.address_ = address_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.AddressResponse) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.AddressResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.AddressResponse other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.AddressResponse.getDefaultInstance()) return this;
      if (!other.address_.isEmpty()) {
        if (address_.isEmpty()) {
          address_ = other.address_;
          bitField0_ |= 0x00000001;
        } else {
          ensureAddressIsMutable();
          address_.addAll(other.address_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ensureAddressIsMutable();
              address_.add(input.readStringRequireUtf8());
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList address_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAddressIsMutable() {
      if (!address_.isModifiable()) {
        address_ = new com.google.protobuf.LazyStringArrayList(address_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * An array of MWEB addresses within the requested range.
     * </pre>
     *
     * <code>repeated string address = 1;</code>
     * @return A list containing the address.
     */
    public com.google.protobuf.ProtocolStringList
        getAddressList() {
      address_.makeImmutable();
      return address_;
    }
    /**
     * <pre>
     * An array of MWEB addresses within the requested range.
     * </pre>
     *
     * <code>repeated string address = 1;</code>
     * @return The count of address.
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <pre>
     * An array of MWEB addresses within the requested range.
     * </pre>
     *
     * <code>repeated string address = 1;</code>
     * @param index The index of the element to return.
     * @return The address at the given index.
     */
    public java.lang.String getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <pre>
     * An array of MWEB addresses within the requested range.
     * </pre>
     *
     * <code>repeated string address = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the address at the given index.
     */
    public com.google.protobuf.ByteString
        getAddressBytes(int index) {
      return address_.getByteString(index);
    }
    /**
     * <pre>
     * An array of MWEB addresses within the requested range.
     * </pre>
     *
     * <code>repeated string address = 1;</code>
     * @param index The index to set the value at.
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAddressIsMutable();
      address_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An array of MWEB addresses within the requested range.
     * </pre>
     *
     * <code>repeated string address = 1;</code>
     * @param value The address to add.
     * @return This builder for chaining.
     */
    public Builder addAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAddressIsMutable();
      address_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An array of MWEB addresses within the requested range.
     * </pre>
     *
     * <code>repeated string address = 1;</code>
     * @param values The address to add.
     * @return This builder for chaining.
     */
    public Builder addAllAddress(
        java.lang.Iterable<java.lang.String> values) {
      ensureAddressIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, address_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An array of MWEB addresses within the requested range.
     * </pre>
     *
     * <code>repeated string address = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      address_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An array of MWEB addresses within the requested range.
     * </pre>
     *
     * <code>repeated string address = 1;</code>
     * @param value The bytes of the address to add.
     * @return This builder for chaining.
     */
    public Builder addAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAddressIsMutable();
      address_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:AddressResponse)
  }

  // @@protoc_insertion_point(class_scope:AddressResponse)
  private static final com.sparrowwallet.sparrow.mweb.proto.AddressResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.AddressResponse();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.AddressResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddressResponse>
      PARSER = new com.google.protobuf.AbstractParser<AddressResponse>() {
    @java.lang.Override
    public AddressResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddressResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddressResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.AddressResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

