// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface BroadcastRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BroadcastRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The raw bytes of the serialized transaction.
   * </pre>
   *
   * <code>bytes raw_tx = 1;</code>
   * @return The rawTx.
   */
  com.google.protobuf.ByteString getRawTx();
}
