// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface CoinswapResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CoinswapResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Output ID of the utxo created by the transaction.
   * </pre>
   *
   * <code>string output_id = 1;</code>
   * @return The outputId.
   */
  java.lang.String getOutputId();
  /**
   * <pre>
   * Output ID of the utxo created by the transaction.
   * </pre>
   *
   * <code>string output_id = 1;</code>
   * @return The bytes for outputId.
   */
  com.google.protobuf.ByteString
      getOutputIdBytes();
}
