// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface CoinswapRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CoinswapRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The scan secret or view key represents the account that
   * the utxo belongs to.
   * </pre>
   *
   * <code>bytes scan_secret = 1;</code>
   * @return The scanSecret.
   */
  com.google.protobuf.ByteString getScanSecret();

  /**
   * <pre>
   * The spend secret is the private key necessary for spending
   * the utxos belonging to the account.
   * </pre>
   *
   * <code>bytes spend_secret = 2;</code>
   * @return The spendSecret.
   */
  com.google.protobuf.ByteString getSpendSecret();

  /**
   * <pre>
   * Output ID of the utxo to request a coinswap for.
   * </pre>
   *
   * <code>string output_id = 3;</code>
   * @return The outputId.
   */
  java.lang.String getOutputId();
  /**
   * <pre>
   * Output ID of the utxo to request a coinswap for.
   * </pre>
   *
   * <code>string output_id = 3;</code>
   * @return The bytes for outputId.
   */
  com.google.protobuf.ByteString
      getOutputIdBytes();

  /**
   * <pre>
   * Address index of the utxo.
   * </pre>
   *
   * <code>uint32 addr_index = 4;</code>
   * @return The addrIndex.
   */
  int getAddrIndex();
}
