// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code CoinswapRequest}
 */
@com.google.protobuf.Generated
public final class CoinswapRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:CoinswapRequest)
    CoinswapRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "CoinswapRequest");
  }
  // Use CoinswapRequest.newBuilder() to construct.
  private CoinswapRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CoinswapRequest() {
    scanSecret_ = com.google.protobuf.ByteString.EMPTY;
    spendSecret_ = com.google.protobuf.ByteString.EMPTY;
    outputId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CoinswapRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CoinswapRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CoinswapRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest.class, com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest.Builder.class);
  }

  public static final int SCAN_SECRET_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString scanSecret_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * The scan secret or view key represents the account that
   * the utxo belongs to.
   * </pre>
   *
   * <code>bytes scan_secret = 1;</code>
   * @return The scanSecret.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getScanSecret() {
    return scanSecret_;
  }

  public static final int SPEND_SECRET_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString spendSecret_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * The spend secret is the private key necessary for spending
   * the utxos belonging to the account.
   * </pre>
   *
   * <code>bytes spend_secret = 2;</code>
   * @return The spendSecret.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSpendSecret() {
    return spendSecret_;
  }

  public static final int OUTPUT_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object outputId_ = "";
  /**
   * <pre>
   * Output ID of the utxo to request a coinswap for.
   * </pre>
   *
   * <code>string output_id = 3;</code>
   * @return The outputId.
   */
  @java.lang.Override
  public java.lang.String getOutputId() {
    java.lang.Object ref = outputId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outputId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Output ID of the utxo to request a coinswap for.
   * </pre>
   *
   * <code>string output_id = 3;</code>
   * @return The bytes for outputId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutputIdBytes() {
    java.lang.Object ref = outputId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outputId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDR_INDEX_FIELD_NUMBER = 4;
  private int addrIndex_ = 0;
  /**
   * <pre>
   * Address index of the utxo.
   * </pre>
   *
   * <code>uint32 addr_index = 4;</code>
   * @return The addrIndex.
   */
  @java.lang.Override
  public int getAddrIndex() {
    return addrIndex_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!scanSecret_.isEmpty()) {
      output.writeBytes(1, scanSecret_);
    }
    if (!spendSecret_.isEmpty()) {
      output.writeBytes(2, spendSecret_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, outputId_);
    }
    if (addrIndex_ != 0) {
      output.writeUInt32(4, addrIndex_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!scanSecret_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, scanSecret_);
    }
    if (!spendSecret_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, spendSecret_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, outputId_);
    }
    if (addrIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, addrIndex_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest other = (com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest) obj;

    if (!getScanSecret()
        .equals(other.getScanSecret())) return false;
    if (!getSpendSecret()
        .equals(other.getSpendSecret())) return false;
    if (!getOutputId()
        .equals(other.getOutputId())) return false;
    if (getAddrIndex()
        != other.getAddrIndex()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCAN_SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getScanSecret().hashCode();
    hash = (37 * hash) + SPEND_SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getSpendSecret().hashCode();
    hash = (37 * hash) + OUTPUT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOutputId().hashCode();
    hash = (37 * hash) + ADDR_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getAddrIndex();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CoinswapRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CoinswapRequest)
      com.sparrowwallet.sparrow.mweb.proto.CoinswapRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CoinswapRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CoinswapRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest.class, com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      scanSecret_ = com.google.protobuf.ByteString.EMPTY;
      spendSecret_ = com.google.protobuf.ByteString.EMPTY;
      outputId_ = "";
      addrIndex_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CoinswapRequest_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest build() {
      com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest result = new com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.scanSecret_ = scanSecret_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.spendSecret_ = spendSecret_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.outputId_ = outputId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.addrIndex_ = addrIndex_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest.getDefaultInstance()) return this;
      if (!other.getScanSecret().isEmpty()) {
        setScanSecret(other.getScanSecret());
      }
      if (!other.getSpendSecret().isEmpty()) {
        setSpendSecret(other.getSpendSecret());
      }
      if (!other.getOutputId().isEmpty()) {
        outputId_ = other.outputId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getAddrIndex() != 0) {
        setAddrIndex(other.getAddrIndex());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              scanSecret_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              spendSecret_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              outputId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              addrIndex_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString scanSecret_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The scan secret or view key represents the account that
     * the utxo belongs to.
     * </pre>
     *
     * <code>bytes scan_secret = 1;</code>
     * @return The scanSecret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getScanSecret() {
      return scanSecret_;
    }
    /**
     * <pre>
     * The scan secret or view key represents the account that
     * the utxo belongs to.
     * </pre>
     *
     * <code>bytes scan_secret = 1;</code>
     * @param value The scanSecret to set.
     * @return This builder for chaining.
     */
    public Builder setScanSecret(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      scanSecret_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The scan secret or view key represents the account that
     * the utxo belongs to.
     * </pre>
     *
     * <code>bytes scan_secret = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearScanSecret() {
      bitField0_ = (bitField0_ & ~0x00000001);
      scanSecret_ = getDefaultInstance().getScanSecret();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString spendSecret_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The spend secret is the private key necessary for spending
     * the utxos belonging to the account.
     * </pre>
     *
     * <code>bytes spend_secret = 2;</code>
     * @return The spendSecret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSpendSecret() {
      return spendSecret_;
    }
    /**
     * <pre>
     * The spend secret is the private key necessary for spending
     * the utxos belonging to the account.
     * </pre>
     *
     * <code>bytes spend_secret = 2;</code>
     * @param value The spendSecret to set.
     * @return This builder for chaining.
     */
    public Builder setSpendSecret(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      spendSecret_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The spend secret is the private key necessary for spending
     * the utxos belonging to the account.
     * </pre>
     *
     * <code>bytes spend_secret = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpendSecret() {
      bitField0_ = (bitField0_ & ~0x00000002);
      spendSecret_ = getDefaultInstance().getSpendSecret();
      onChanged();
      return this;
    }

    private java.lang.Object outputId_ = "";
    /**
     * <pre>
     * Output ID of the utxo to request a coinswap for.
     * </pre>
     *
     * <code>string output_id = 3;</code>
     * @return The outputId.
     */
    public java.lang.String getOutputId() {
      java.lang.Object ref = outputId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Output ID of the utxo to request a coinswap for.
     * </pre>
     *
     * <code>string output_id = 3;</code>
     * @return The bytes for outputId.
     */
    public com.google.protobuf.ByteString
        getOutputIdBytes() {
      java.lang.Object ref = outputId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Output ID of the utxo to request a coinswap for.
     * </pre>
     *
     * <code>string output_id = 3;</code>
     * @param value The outputId to set.
     * @return This builder for chaining.
     */
    public Builder setOutputId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      outputId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Output ID of the utxo to request a coinswap for.
     * </pre>
     *
     * <code>string output_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputId() {
      outputId_ = getDefaultInstance().getOutputId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Output ID of the utxo to request a coinswap for.
     * </pre>
     *
     * <code>string output_id = 3;</code>
     * @param value The bytes for outputId to set.
     * @return This builder for chaining.
     */
    public Builder setOutputIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      outputId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int addrIndex_ ;
    /**
     * <pre>
     * Address index of the utxo.
     * </pre>
     *
     * <code>uint32 addr_index = 4;</code>
     * @return The addrIndex.
     */
    @java.lang.Override
    public int getAddrIndex() {
      return addrIndex_;
    }
    /**
     * <pre>
     * Address index of the utxo.
     * </pre>
     *
     * <code>uint32 addr_index = 4;</code>
     * @param value The addrIndex to set.
     * @return This builder for chaining.
     */
    public Builder setAddrIndex(int value) {

      addrIndex_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Address index of the utxo.
     * </pre>
     *
     * <code>uint32 addr_index = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddrIndex() {
      bitField0_ = (bitField0_ & ~0x00000008);
      addrIndex_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CoinswapRequest)
  }

  // @@protoc_insertion_point(class_scope:CoinswapRequest)
  private static final com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CoinswapRequest>
      PARSER = new com.google.protobuf.AbstractParser<CoinswapRequest>() {
    @java.lang.Override
    public CoinswapRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CoinswapRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CoinswapRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.CoinswapRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

