// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code CreateResponse}
 */
@com.google.protobuf.Generated
public final class CreateResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:CreateResponse)
    CreateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "CreateResponse");
  }
  // Use CreateResponse.newBuilder() to construct.
  private CreateResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateResponse() {
    rawTx_ = com.google.protobuf.ByteString.EMPTY;
    outputId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CreateResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CreateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CreateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.CreateResponse.class, com.sparrowwallet.sparrow.mweb.proto.CreateResponse.Builder.class);
  }

  public static final int RAW_TX_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString rawTx_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * The raw bytes of the serialized transaction. It will contain
   * a single TxOut representing the peg-in required. From this
   * it is possible to determine the addtional fee that was added
   * by the MWEB transaction.
   * </pre>
   *
   * <code>bytes raw_tx = 1;</code>
   * @return The rawTx.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRawTx() {
    return rawTx_;
  }

  public static final int OUTPUT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList outputId_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * The output IDs of any utxos created by the transaction,
   * in the same order as in the template.
   * </pre>
   *
   * <code>repeated string output_id = 2;</code>
   * @return A list containing the outputId.
   */
  public com.google.protobuf.ProtocolStringList
      getOutputIdList() {
    return outputId_;
  }
  /**
   * <pre>
   * The output IDs of any utxos created by the transaction,
   * in the same order as in the template.
   * </pre>
   *
   * <code>repeated string output_id = 2;</code>
   * @return The count of outputId.
   */
  public int getOutputIdCount() {
    return outputId_.size();
  }
  /**
   * <pre>
   * The output IDs of any utxos created by the transaction,
   * in the same order as in the template.
   * </pre>
   *
   * <code>repeated string output_id = 2;</code>
   * @param index The index of the element to return.
   * @return The outputId at the given index.
   */
  public java.lang.String getOutputId(int index) {
    return outputId_.get(index);
  }
  /**
   * <pre>
   * The output IDs of any utxos created by the transaction,
   * in the same order as in the template.
   * </pre>
   *
   * <code>repeated string output_id = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the outputId at the given index.
   */
  public com.google.protobuf.ByteString
      getOutputIdBytes(int index) {
    return outputId_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!rawTx_.isEmpty()) {
      output.writeBytes(1, rawTx_);
    }
    for (int i = 0; i < outputId_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, outputId_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!rawTx_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, rawTx_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < outputId_.size(); i++) {
        dataSize += computeStringSizeNoTag(outputId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOutputIdList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.CreateResponse)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.CreateResponse other = (com.sparrowwallet.sparrow.mweb.proto.CreateResponse) obj;

    if (!getRawTx()
        .equals(other.getRawTx())) return false;
    if (!getOutputIdList()
        .equals(other.getOutputIdList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RAW_TX_FIELD_NUMBER;
    hash = (53 * hash) + getRawTx().hashCode();
    if (getOutputIdCount() > 0) {
      hash = (37 * hash) + OUTPUT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getOutputIdList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.CreateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreateResponse)
      com.sparrowwallet.sparrow.mweb.proto.CreateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CreateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CreateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.CreateResponse.class, com.sparrowwallet.sparrow.mweb.proto.CreateResponse.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.CreateResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rawTx_ = com.google.protobuf.ByteString.EMPTY;
      outputId_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_CreateResponse_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.CreateResponse getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.CreateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.CreateResponse build() {
      com.sparrowwallet.sparrow.mweb.proto.CreateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.CreateResponse buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.CreateResponse result = new com.sparrowwallet.sparrow.mweb.proto.CreateResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.CreateResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rawTx_ = rawTx_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        outputId_.makeImmutable();
        result.outputId_ = outputId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.CreateResponse) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.CreateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.CreateResponse other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.CreateResponse.getDefaultInstance()) return this;
      if (!other.getRawTx().isEmpty()) {
        setRawTx(other.getRawTx());
      }
      if (!other.outputId_.isEmpty()) {
        if (outputId_.isEmpty()) {
          outputId_ = other.outputId_;
          bitField0_ |= 0x00000002;
        } else {
          ensureOutputIdIsMutable();
          outputId_.addAll(other.outputId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              rawTx_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              ensureOutputIdIsMutable();
              outputId_.add(input.readStringRequireUtf8());
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString rawTx_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The raw bytes of the serialized transaction. It will contain
     * a single TxOut representing the peg-in required. From this
     * it is possible to determine the addtional fee that was added
     * by the MWEB transaction.
     * </pre>
     *
     * <code>bytes raw_tx = 1;</code>
     * @return The rawTx.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRawTx() {
      return rawTx_;
    }
    /**
     * <pre>
     * The raw bytes of the serialized transaction. It will contain
     * a single TxOut representing the peg-in required. From this
     * it is possible to determine the addtional fee that was added
     * by the MWEB transaction.
     * </pre>
     *
     * <code>bytes raw_tx = 1;</code>
     * @param value The rawTx to set.
     * @return This builder for chaining.
     */
    public Builder setRawTx(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      rawTx_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The raw bytes of the serialized transaction. It will contain
     * a single TxOut representing the peg-in required. From this
     * it is possible to determine the addtional fee that was added
     * by the MWEB transaction.
     * </pre>
     *
     * <code>bytes raw_tx = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRawTx() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rawTx_ = getDefaultInstance().getRawTx();
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList outputId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureOutputIdIsMutable() {
      if (!outputId_.isModifiable()) {
        outputId_ = new com.google.protobuf.LazyStringArrayList(outputId_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * The output IDs of any utxos created by the transaction,
     * in the same order as in the template.
     * </pre>
     *
     * <code>repeated string output_id = 2;</code>
     * @return A list containing the outputId.
     */
    public com.google.protobuf.ProtocolStringList
        getOutputIdList() {
      outputId_.makeImmutable();
      return outputId_;
    }
    /**
     * <pre>
     * The output IDs of any utxos created by the transaction,
     * in the same order as in the template.
     * </pre>
     *
     * <code>repeated string output_id = 2;</code>
     * @return The count of outputId.
     */
    public int getOutputIdCount() {
      return outputId_.size();
    }
    /**
     * <pre>
     * The output IDs of any utxos created by the transaction,
     * in the same order as in the template.
     * </pre>
     *
     * <code>repeated string output_id = 2;</code>
     * @param index The index of the element to return.
     * @return The outputId at the given index.
     */
    public java.lang.String getOutputId(int index) {
      return outputId_.get(index);
    }
    /**
     * <pre>
     * The output IDs of any utxos created by the transaction,
     * in the same order as in the template.
     * </pre>
     *
     * <code>repeated string output_id = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the outputId at the given index.
     */
    public com.google.protobuf.ByteString
        getOutputIdBytes(int index) {
      return outputId_.getByteString(index);
    }
    /**
     * <pre>
     * The output IDs of any utxos created by the transaction,
     * in the same order as in the template.
     * </pre>
     *
     * <code>repeated string output_id = 2;</code>
     * @param index The index to set the value at.
     * @param value The outputId to set.
     * @return This builder for chaining.
     */
    public Builder setOutputId(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOutputIdIsMutable();
      outputId_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output IDs of any utxos created by the transaction,
     * in the same order as in the template.
     * </pre>
     *
     * <code>repeated string output_id = 2;</code>
     * @param value The outputId to add.
     * @return This builder for chaining.
     */
    public Builder addOutputId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOutputIdIsMutable();
      outputId_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output IDs of any utxos created by the transaction,
     * in the same order as in the template.
     * </pre>
     *
     * <code>repeated string output_id = 2;</code>
     * @param values The outputId to add.
     * @return This builder for chaining.
     */
    public Builder addAllOutputId(
        java.lang.Iterable<java.lang.String> values) {
      ensureOutputIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, outputId_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output IDs of any utxos created by the transaction,
     * in the same order as in the template.
     * </pre>
     *
     * <code>repeated string output_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputId() {
      outputId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output IDs of any utxos created by the transaction,
     * in the same order as in the template.
     * </pre>
     *
     * <code>repeated string output_id = 2;</code>
     * @param value The bytes of the outputId to add.
     * @return This builder for chaining.
     */
    public Builder addOutputIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureOutputIdIsMutable();
      outputId_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CreateResponse)
  }

  // @@protoc_insertion_point(class_scope:CreateResponse)
  private static final com.sparrowwallet.sparrow.mweb.proto.CreateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.CreateResponse();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.CreateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateResponse>() {
    @java.lang.Override
    public CreateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.CreateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

