// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface PsbtGetRecipientsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PsbtGetRecipientsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The psbtB64.
   */
  java.lang.String getPsbtB64();
  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The bytes for psbtB64.
   */
  com.google.protobuf.ByteString
      getPsbtB64Bytes();
}
