// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface PsbtAddInputRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PsbtAddInputRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The psbtB64.
   */
  java.lang.String getPsbtB64();
  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The bytes for psbtB64.
   */
  com.google.protobuf.ByteString
      getPsbtB64Bytes();

  /**
   * <pre>
   * The scan secret or view key represents the account that
   * the utxos being spent belong to.
   * </pre>
   *
   * <code>bytes scan_secret = 2;</code>
   * @return The scanSecret.
   */
  com.google.protobuf.ByteString getScanSecret();

  /**
   * <pre>
   * The output ID of the utxo.
   * </pre>
   *
   * <code>string output_id = 3;</code>
   * @return The outputId.
   */
  java.lang.String getOutputId();
  /**
   * <pre>
   * The output ID of the utxo.
   * </pre>
   *
   * <code>string output_id = 3;</code>
   * @return The bytes for outputId.
   */
  com.google.protobuf.ByteString
      getOutputIdBytes();

  /**
   * <pre>
   * The address index of the utxo.
   * </pre>
   *
   * <code>uint32 address_index = 4;</code>
   * @return The addressIndex.
   */
  int getAddressIndex();

  /**
   * <pre>
   * The fee rate per KB in litoshis.
   * </pre>
   *
   * <code>uint64 fee_rate_per_kb = 5;</code>
   * @return The feeRatePerKb.
   */
  long getFeeRatePerKb();
}
