// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface PsbtCreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PsbtCreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The raw bytes of the serialized transaction.
   * </pre>
   *
   * <code>bytes raw_tx = 1;</code>
   * @return The rawTx.
   */
  com.google.protobuf.ByteString getRawTx();

  /**
   * <pre>
   * Witness utxos for each input.
   * </pre>
   *
   * <code>repeated .TxOut witness_utxo = 2;</code>
   */
  java.util.List<com.sparrowwallet.sparrow.mweb.proto.TxOut> 
      getWitnessUtxoList();
  /**
   * <pre>
   * Witness utxos for each input.
   * </pre>
   *
   * <code>repeated .TxOut witness_utxo = 2;</code>
   */
  com.sparrowwallet.sparrow.mweb.proto.TxOut getWitnessUtxo(int index);
  /**
   * <pre>
   * Witness utxos for each input.
   * </pre>
   *
   * <code>repeated .TxOut witness_utxo = 2;</code>
   */
  int getWitnessUtxoCount();
  /**
   * <pre>
   * Witness utxos for each input.
   * </pre>
   *
   * <code>repeated .TxOut witness_utxo = 2;</code>
   */
  java.util.List<? extends com.sparrowwallet.sparrow.mweb.proto.TxOutOrBuilder> 
      getWitnessUtxoOrBuilderList();
  /**
   * <pre>
   * Witness utxos for each input.
   * </pre>
   *
   * <code>repeated .TxOut witness_utxo = 2;</code>
   */
  com.sparrowwallet.sparrow.mweb.proto.TxOutOrBuilder getWitnessUtxoOrBuilder(
      int index);
}
