// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code PsbtAddInputRequest}
 */
@com.google.protobuf.Generated
public final class PsbtAddInputRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PsbtAddInputRequest)
    PsbtAddInputRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "PsbtAddInputRequest");
  }
  // Use PsbtAddInputRequest.newBuilder() to construct.
  private PsbtAddInputRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PsbtAddInputRequest() {
    psbtB64_ = "";
    scanSecret_ = com.google.protobuf.ByteString.EMPTY;
    outputId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddInputRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddInputRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddInputRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest.class, com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest.Builder.class);
  }

  public static final int PSBT_B64_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object psbtB64_ = "";
  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The psbtB64.
   */
  @java.lang.Override
  public java.lang.String getPsbtB64() {
    java.lang.Object ref = psbtB64_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      psbtB64_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The bytes for psbtB64.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPsbtB64Bytes() {
    java.lang.Object ref = psbtB64_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      psbtB64_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCAN_SECRET_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString scanSecret_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * The scan secret or view key represents the account that
   * the utxos being spent belong to.
   * </pre>
   *
   * <code>bytes scan_secret = 2;</code>
   * @return The scanSecret.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getScanSecret() {
    return scanSecret_;
  }

  public static final int OUTPUT_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object outputId_ = "";
  /**
   * <pre>
   * The output ID of the utxo.
   * </pre>
   *
   * <code>string output_id = 3;</code>
   * @return The outputId.
   */
  @java.lang.Override
  public java.lang.String getOutputId() {
    java.lang.Object ref = outputId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outputId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The output ID of the utxo.
   * </pre>
   *
   * <code>string output_id = 3;</code>
   * @return The bytes for outputId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutputIdBytes() {
    java.lang.Object ref = outputId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outputId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_INDEX_FIELD_NUMBER = 4;
  private int addressIndex_ = 0;
  /**
   * <pre>
   * The address index of the utxo.
   * </pre>
   *
   * <code>uint32 address_index = 4;</code>
   * @return The addressIndex.
   */
  @java.lang.Override
  public int getAddressIndex() {
    return addressIndex_;
  }

  public static final int FEE_RATE_PER_KB_FIELD_NUMBER = 5;
  private long feeRatePerKb_ = 0L;
  /**
   * <pre>
   * The fee rate per KB in litoshis.
   * </pre>
   *
   * <code>uint64 fee_rate_per_kb = 5;</code>
   * @return The feeRatePerKb.
   */
  @java.lang.Override
  public long getFeeRatePerKb() {
    return feeRatePerKb_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(psbtB64_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, psbtB64_);
    }
    if (!scanSecret_.isEmpty()) {
      output.writeBytes(2, scanSecret_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, outputId_);
    }
    if (addressIndex_ != 0) {
      output.writeUInt32(4, addressIndex_);
    }
    if (feeRatePerKb_ != 0L) {
      output.writeUInt64(5, feeRatePerKb_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(psbtB64_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, psbtB64_);
    }
    if (!scanSecret_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, scanSecret_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, outputId_);
    }
    if (addressIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, addressIndex_);
    }
    if (feeRatePerKb_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, feeRatePerKb_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest other = (com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest) obj;

    if (!getPsbtB64()
        .equals(other.getPsbtB64())) return false;
    if (!getScanSecret()
        .equals(other.getScanSecret())) return false;
    if (!getOutputId()
        .equals(other.getOutputId())) return false;
    if (getAddressIndex()
        != other.getAddressIndex()) return false;
    if (getFeeRatePerKb()
        != other.getFeeRatePerKb()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PSBT_B64_FIELD_NUMBER;
    hash = (53 * hash) + getPsbtB64().hashCode();
    hash = (37 * hash) + SCAN_SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getScanSecret().hashCode();
    hash = (37 * hash) + OUTPUT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOutputId().hashCode();
    hash = (37 * hash) + ADDRESS_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getAddressIndex();
    hash = (37 * hash) + FEE_RATE_PER_KB_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFeeRatePerKb());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PsbtAddInputRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PsbtAddInputRequest)
      com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddInputRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddInputRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest.class, com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      psbtB64_ = "";
      scanSecret_ = com.google.protobuf.ByteString.EMPTY;
      outputId_ = "";
      addressIndex_ = 0;
      feeRatePerKb_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddInputRequest_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest build() {
      com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest result = new com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.psbtB64_ = psbtB64_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.scanSecret_ = scanSecret_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.outputId_ = outputId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.addressIndex_ = addressIndex_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.feeRatePerKb_ = feeRatePerKb_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest.getDefaultInstance()) return this;
      if (!other.getPsbtB64().isEmpty()) {
        psbtB64_ = other.psbtB64_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getScanSecret().isEmpty()) {
        setScanSecret(other.getScanSecret());
      }
      if (!other.getOutputId().isEmpty()) {
        outputId_ = other.outputId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getAddressIndex() != 0) {
        setAddressIndex(other.getAddressIndex());
      }
      if (other.getFeeRatePerKb() != 0L) {
        setFeeRatePerKb(other.getFeeRatePerKb());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              psbtB64_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              scanSecret_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              outputId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              addressIndex_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              feeRatePerKb_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object psbtB64_ = "";
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @return The psbtB64.
     */
    public java.lang.String getPsbtB64() {
      java.lang.Object ref = psbtB64_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        psbtB64_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @return The bytes for psbtB64.
     */
    public com.google.protobuf.ByteString
        getPsbtB64Bytes() {
      java.lang.Object ref = psbtB64_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        psbtB64_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @param value The psbtB64 to set.
     * @return This builder for chaining.
     */
    public Builder setPsbtB64(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      psbtB64_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPsbtB64() {
      psbtB64_ = getDefaultInstance().getPsbtB64();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @param value The bytes for psbtB64 to set.
     * @return This builder for chaining.
     */
    public Builder setPsbtB64Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      psbtB64_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString scanSecret_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The scan secret or view key represents the account that
     * the utxos being spent belong to.
     * </pre>
     *
     * <code>bytes scan_secret = 2;</code>
     * @return The scanSecret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getScanSecret() {
      return scanSecret_;
    }
    /**
     * <pre>
     * The scan secret or view key represents the account that
     * the utxos being spent belong to.
     * </pre>
     *
     * <code>bytes scan_secret = 2;</code>
     * @param value The scanSecret to set.
     * @return This builder for chaining.
     */
    public Builder setScanSecret(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      scanSecret_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The scan secret or view key represents the account that
     * the utxos being spent belong to.
     * </pre>
     *
     * <code>bytes scan_secret = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearScanSecret() {
      bitField0_ = (bitField0_ & ~0x00000002);
      scanSecret_ = getDefaultInstance().getScanSecret();
      onChanged();
      return this;
    }

    private java.lang.Object outputId_ = "";
    /**
     * <pre>
     * The output ID of the utxo.
     * </pre>
     *
     * <code>string output_id = 3;</code>
     * @return The outputId.
     */
    public java.lang.String getOutputId() {
      java.lang.Object ref = outputId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The output ID of the utxo.
     * </pre>
     *
     * <code>string output_id = 3;</code>
     * @return The bytes for outputId.
     */
    public com.google.protobuf.ByteString
        getOutputIdBytes() {
      java.lang.Object ref = outputId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The output ID of the utxo.
     * </pre>
     *
     * <code>string output_id = 3;</code>
     * @param value The outputId to set.
     * @return This builder for chaining.
     */
    public Builder setOutputId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      outputId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output ID of the utxo.
     * </pre>
     *
     * <code>string output_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputId() {
      outputId_ = getDefaultInstance().getOutputId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output ID of the utxo.
     * </pre>
     *
     * <code>string output_id = 3;</code>
     * @param value The bytes for outputId to set.
     * @return This builder for chaining.
     */
    public Builder setOutputIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      outputId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int addressIndex_ ;
    /**
     * <pre>
     * The address index of the utxo.
     * </pre>
     *
     * <code>uint32 address_index = 4;</code>
     * @return The addressIndex.
     */
    @java.lang.Override
    public int getAddressIndex() {
      return addressIndex_;
    }
    /**
     * <pre>
     * The address index of the utxo.
     * </pre>
     *
     * <code>uint32 address_index = 4;</code>
     * @param value The addressIndex to set.
     * @return This builder for chaining.
     */
    public Builder setAddressIndex(int value) {

      addressIndex_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The address index of the utxo.
     * </pre>
     *
     * <code>uint32 address_index = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddressIndex() {
      bitField0_ = (bitField0_ & ~0x00000008);
      addressIndex_ = 0;
      onChanged();
      return this;
    }

    private long feeRatePerKb_ ;
    /**
     * <pre>
     * The fee rate per KB in litoshis.
     * </pre>
     *
     * <code>uint64 fee_rate_per_kb = 5;</code>
     * @return The feeRatePerKb.
     */
    @java.lang.Override
    public long getFeeRatePerKb() {
      return feeRatePerKb_;
    }
    /**
     * <pre>
     * The fee rate per KB in litoshis.
     * </pre>
     *
     * <code>uint64 fee_rate_per_kb = 5;</code>
     * @param value The feeRatePerKb to set.
     * @return This builder for chaining.
     */
    public Builder setFeeRatePerKb(long value) {

      feeRatePerKb_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The fee rate per KB in litoshis.
     * </pre>
     *
     * <code>uint64 fee_rate_per_kb = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFeeRatePerKb() {
      bitField0_ = (bitField0_ & ~0x00000010);
      feeRatePerKb_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PsbtAddInputRequest)
  }

  // @@protoc_insertion_point(class_scope:PsbtAddInputRequest)
  private static final com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PsbtAddInputRequest>
      PARSER = new com.google.protobuf.AbstractParser<PsbtAddInputRequest>() {
    @java.lang.Override
    public PsbtAddInputRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PsbtAddInputRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PsbtAddInputRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.PsbtAddInputRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

