// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code PsbtCreateRequest}
 */
@com.google.protobuf.Generated
public final class PsbtCreateRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PsbtCreateRequest)
    PsbtCreateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "PsbtCreateRequest");
  }
  // Use PsbtCreateRequest.newBuilder() to construct.
  private PsbtCreateRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PsbtCreateRequest() {
    rawTx_ = com.google.protobuf.ByteString.EMPTY;
    witnessUtxo_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtCreateRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtCreateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtCreateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest.class, com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest.Builder.class);
  }

  public static final int RAW_TX_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString rawTx_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * The raw bytes of the serialized transaction.
   * </pre>
   *
   * <code>bytes raw_tx = 1;</code>
   * @return The rawTx.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRawTx() {
    return rawTx_;
  }

  public static final int WITNESS_UTXO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.sparrowwallet.sparrow.mweb.proto.TxOut> witnessUtxo_;
  /**
   * <pre>
   * Witness utxos for each input.
   * </pre>
   *
   * <code>repeated .TxOut witness_utxo = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.sparrowwallet.sparrow.mweb.proto.TxOut> getWitnessUtxoList() {
    return witnessUtxo_;
  }
  /**
   * <pre>
   * Witness utxos for each input.
   * </pre>
   *
   * <code>repeated .TxOut witness_utxo = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.sparrowwallet.sparrow.mweb.proto.TxOutOrBuilder> 
      getWitnessUtxoOrBuilderList() {
    return witnessUtxo_;
  }
  /**
   * <pre>
   * Witness utxos for each input.
   * </pre>
   *
   * <code>repeated .TxOut witness_utxo = 2;</code>
   */
  @java.lang.Override
  public int getWitnessUtxoCount() {
    return witnessUtxo_.size();
  }
  /**
   * <pre>
   * Witness utxos for each input.
   * </pre>
   *
   * <code>repeated .TxOut witness_utxo = 2;</code>
   */
  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.TxOut getWitnessUtxo(int index) {
    return witnessUtxo_.get(index);
  }
  /**
   * <pre>
   * Witness utxos for each input.
   * </pre>
   *
   * <code>repeated .TxOut witness_utxo = 2;</code>
   */
  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.TxOutOrBuilder getWitnessUtxoOrBuilder(
      int index) {
    return witnessUtxo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!rawTx_.isEmpty()) {
      output.writeBytes(1, rawTx_);
    }
    for (int i = 0; i < witnessUtxo_.size(); i++) {
      output.writeMessage(2, witnessUtxo_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!rawTx_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, rawTx_);
    }

        {
          final int count = witnessUtxo_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(witnessUtxo_.get(i));
          }
          size += 1 * count;
        }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest other = (com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest) obj;

    if (!getRawTx()
        .equals(other.getRawTx())) return false;
    if (!getWitnessUtxoList()
        .equals(other.getWitnessUtxoList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RAW_TX_FIELD_NUMBER;
    hash = (53 * hash) + getRawTx().hashCode();
    if (getWitnessUtxoCount() > 0) {
      hash = (37 * hash) + WITNESS_UTXO_FIELD_NUMBER;
      hash = (53 * hash) + getWitnessUtxoList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PsbtCreateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PsbtCreateRequest)
      com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtCreateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtCreateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest.class, com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rawTx_ = com.google.protobuf.ByteString.EMPTY;
      if (witnessUtxoBuilder_ == null) {
        witnessUtxo_ = java.util.Collections.emptyList();
      } else {
        witnessUtxo_ = null;
        witnessUtxoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtCreateRequest_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest build() {
      com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest result = new com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest result) {
      if (witnessUtxoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          witnessUtxo_ = java.util.Collections.unmodifiableList(witnessUtxo_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.witnessUtxo_ = witnessUtxo_;
      } else {
        result.witnessUtxo_ = witnessUtxoBuilder_.build();
      }
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rawTx_ = rawTx_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest.getDefaultInstance()) return this;
      if (!other.getRawTx().isEmpty()) {
        setRawTx(other.getRawTx());
      }
      if (witnessUtxoBuilder_ == null) {
        if (!other.witnessUtxo_.isEmpty()) {
          if (witnessUtxo_.isEmpty()) {
            witnessUtxo_ = other.witnessUtxo_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureWitnessUtxoIsMutable();
            witnessUtxo_.addAll(other.witnessUtxo_);
          }
          onChanged();
        }
      } else {
        if (!other.witnessUtxo_.isEmpty()) {
          if (witnessUtxoBuilder_.isEmpty()) {
            witnessUtxoBuilder_.dispose();
            witnessUtxoBuilder_ = null;
            witnessUtxo_ = other.witnessUtxo_;
            bitField0_ = (bitField0_ & ~0x00000002);
            witnessUtxoBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetWitnessUtxoFieldBuilder() : null;
          } else {
            witnessUtxoBuilder_.addAllMessages(other.witnessUtxo_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              rawTx_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.sparrowwallet.sparrow.mweb.proto.TxOut m =
                  input.readMessage(
                      com.sparrowwallet.sparrow.mweb.proto.TxOut.parser(),
                      extensionRegistry);
              if (witnessUtxoBuilder_ == null) {
                ensureWitnessUtxoIsMutable();
                witnessUtxo_.add(m);
              } else {
                witnessUtxoBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString rawTx_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The raw bytes of the serialized transaction.
     * </pre>
     *
     * <code>bytes raw_tx = 1;</code>
     * @return The rawTx.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRawTx() {
      return rawTx_;
    }
    /**
     * <pre>
     * The raw bytes of the serialized transaction.
     * </pre>
     *
     * <code>bytes raw_tx = 1;</code>
     * @param value The rawTx to set.
     * @return This builder for chaining.
     */
    public Builder setRawTx(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      rawTx_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The raw bytes of the serialized transaction.
     * </pre>
     *
     * <code>bytes raw_tx = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRawTx() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rawTx_ = getDefaultInstance().getRawTx();
      onChanged();
      return this;
    }

    private java.util.List<com.sparrowwallet.sparrow.mweb.proto.TxOut> witnessUtxo_ =
      java.util.Collections.emptyList();
    private void ensureWitnessUtxoIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        witnessUtxo_ = new java.util.ArrayList<com.sparrowwallet.sparrow.mweb.proto.TxOut>(witnessUtxo_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.sparrowwallet.sparrow.mweb.proto.TxOut, com.sparrowwallet.sparrow.mweb.proto.TxOut.Builder, com.sparrowwallet.sparrow.mweb.proto.TxOutOrBuilder> witnessUtxoBuilder_;

    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public java.util.List<com.sparrowwallet.sparrow.mweb.proto.TxOut> getWitnessUtxoList() {
      if (witnessUtxoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(witnessUtxo_);
      } else {
        return witnessUtxoBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public int getWitnessUtxoCount() {
      if (witnessUtxoBuilder_ == null) {
        return witnessUtxo_.size();
      } else {
        return witnessUtxoBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.TxOut getWitnessUtxo(int index) {
      if (witnessUtxoBuilder_ == null) {
        return witnessUtxo_.get(index);
      } else {
        return witnessUtxoBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public Builder setWitnessUtxo(
        int index, com.sparrowwallet.sparrow.mweb.proto.TxOut value) {
      if (witnessUtxoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWitnessUtxoIsMutable();
        witnessUtxo_.set(index, value);
        onChanged();
      } else {
        witnessUtxoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public Builder setWitnessUtxo(
        int index, com.sparrowwallet.sparrow.mweb.proto.TxOut.Builder builderForValue) {
      if (witnessUtxoBuilder_ == null) {
        ensureWitnessUtxoIsMutable();
        witnessUtxo_.set(index, builderForValue.build());
        onChanged();
      } else {
        witnessUtxoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public Builder addWitnessUtxo(com.sparrowwallet.sparrow.mweb.proto.TxOut value) {
      if (witnessUtxoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWitnessUtxoIsMutable();
        witnessUtxo_.add(value);
        onChanged();
      } else {
        witnessUtxoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public Builder addWitnessUtxo(
        int index, com.sparrowwallet.sparrow.mweb.proto.TxOut value) {
      if (witnessUtxoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWitnessUtxoIsMutable();
        witnessUtxo_.add(index, value);
        onChanged();
      } else {
        witnessUtxoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public Builder addWitnessUtxo(
        com.sparrowwallet.sparrow.mweb.proto.TxOut.Builder builderForValue) {
      if (witnessUtxoBuilder_ == null) {
        ensureWitnessUtxoIsMutable();
        witnessUtxo_.add(builderForValue.build());
        onChanged();
      } else {
        witnessUtxoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public Builder addWitnessUtxo(
        int index, com.sparrowwallet.sparrow.mweb.proto.TxOut.Builder builderForValue) {
      if (witnessUtxoBuilder_ == null) {
        ensureWitnessUtxoIsMutable();
        witnessUtxo_.add(index, builderForValue.build());
        onChanged();
      } else {
        witnessUtxoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public Builder addAllWitnessUtxo(
        java.lang.Iterable<? extends com.sparrowwallet.sparrow.mweb.proto.TxOut> values) {
      if (witnessUtxoBuilder_ == null) {
        ensureWitnessUtxoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, witnessUtxo_);
        onChanged();
      } else {
        witnessUtxoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public Builder clearWitnessUtxo() {
      if (witnessUtxoBuilder_ == null) {
        witnessUtxo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        witnessUtxoBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public Builder removeWitnessUtxo(int index) {
      if (witnessUtxoBuilder_ == null) {
        ensureWitnessUtxoIsMutable();
        witnessUtxo_.remove(index);
        onChanged();
      } else {
        witnessUtxoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.TxOut.Builder getWitnessUtxoBuilder(
        int index) {
      return internalGetWitnessUtxoFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.TxOutOrBuilder getWitnessUtxoOrBuilder(
        int index) {
      if (witnessUtxoBuilder_ == null) {
        return witnessUtxo_.get(index);  } else {
        return witnessUtxoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public java.util.List<? extends com.sparrowwallet.sparrow.mweb.proto.TxOutOrBuilder> 
         getWitnessUtxoOrBuilderList() {
      if (witnessUtxoBuilder_ != null) {
        return witnessUtxoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(witnessUtxo_);
      }
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.TxOut.Builder addWitnessUtxoBuilder() {
      return internalGetWitnessUtxoFieldBuilder().addBuilder(
          com.sparrowwallet.sparrow.mweb.proto.TxOut.getDefaultInstance());
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.TxOut.Builder addWitnessUtxoBuilder(
        int index) {
      return internalGetWitnessUtxoFieldBuilder().addBuilder(
          index, com.sparrowwallet.sparrow.mweb.proto.TxOut.getDefaultInstance());
    }
    /**
     * <pre>
     * Witness utxos for each input.
     * </pre>
     *
     * <code>repeated .TxOut witness_utxo = 2;</code>
     */
    public java.util.List<com.sparrowwallet.sparrow.mweb.proto.TxOut.Builder> 
         getWitnessUtxoBuilderList() {
      return internalGetWitnessUtxoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.sparrowwallet.sparrow.mweb.proto.TxOut, com.sparrowwallet.sparrow.mweb.proto.TxOut.Builder, com.sparrowwallet.sparrow.mweb.proto.TxOutOrBuilder> 
        internalGetWitnessUtxoFieldBuilder() {
      if (witnessUtxoBuilder_ == null) {
        witnessUtxoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.sparrowwallet.sparrow.mweb.proto.TxOut, com.sparrowwallet.sparrow.mweb.proto.TxOut.Builder, com.sparrowwallet.sparrow.mweb.proto.TxOutOrBuilder>(
                witnessUtxo_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        witnessUtxo_ = null;
      }
      return witnessUtxoBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:PsbtCreateRequest)
  }

  // @@protoc_insertion_point(class_scope:PsbtCreateRequest)
  private static final com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PsbtCreateRequest>
      PARSER = new com.google.protobuf.AbstractParser<PsbtCreateRequest>() {
    @java.lang.Override
    public PsbtCreateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PsbtCreateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PsbtCreateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.PsbtCreateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

