// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface PsbtSignRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PsbtSignRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The psbtB64.
   */
  java.lang.String getPsbtB64();
  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The bytes for psbtB64.
   */
  com.google.protobuf.ByteString
      getPsbtB64Bytes();

  /**
   * <pre>
   * The scan secret or view key represents the account that
   * the utxos being spent belong to.
   * </pre>
   *
   * <code>bytes scan_secret = 2;</code>
   * @return The scanSecret.
   */
  com.google.protobuf.ByteString getScanSecret();

  /**
   * <pre>
   * The spend secret is the private key necessary for spending
   * the utxos belonging to the account.
   * </pre>
   *
   * <code>bytes spend_secret = 3;</code>
   * @return The spendSecret.
   */
  com.google.protobuf.ByteString getSpendSecret();
}
