// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code PsbtAddRecipientRequest}
 */
@com.google.protobuf.Generated
public final class PsbtAddRecipientRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PsbtAddRecipientRequest)
    PsbtAddRecipientRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "PsbtAddRecipientRequest");
  }
  // Use PsbtAddRecipientRequest.newBuilder() to construct.
  private PsbtAddRecipientRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PsbtAddRecipientRequest() {
    psbtB64_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddRecipientRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddRecipientRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddRecipientRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest.class, com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PSBT_B64_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object psbtB64_ = "";
  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The psbtB64.
   */
  @java.lang.Override
  public java.lang.String getPsbtB64() {
    java.lang.Object ref = psbtB64_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      psbtB64_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The bytes for psbtB64.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPsbtB64Bytes() {
    java.lang.Object ref = psbtB64_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      psbtB64_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECIPIENT_FIELD_NUMBER = 2;
  private com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient recipient_;
  /**
   * <code>.PsbtRecipient recipient = 2;</code>
   * @return Whether the recipient field is set.
   */
  @java.lang.Override
  public boolean hasRecipient() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.PsbtRecipient recipient = 2;</code>
   * @return The recipient.
   */
  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient getRecipient() {
    return recipient_ == null ? com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.getDefaultInstance() : recipient_;
  }
  /**
   * <code>.PsbtRecipient recipient = 2;</code>
   */
  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder getRecipientOrBuilder() {
    return recipient_ == null ? com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.getDefaultInstance() : recipient_;
  }

  public static final int FEE_RATE_PER_KB_FIELD_NUMBER = 3;
  private long feeRatePerKb_ = 0L;
  /**
   * <pre>
   * The fee rate per KB in litoshis.
   * </pre>
   *
   * <code>uint64 fee_rate_per_kb = 3;</code>
   * @return The feeRatePerKb.
   */
  @java.lang.Override
  public long getFeeRatePerKb() {
    return feeRatePerKb_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(psbtB64_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, psbtB64_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getRecipient());
    }
    if (feeRatePerKb_ != 0L) {
      output.writeUInt64(3, feeRatePerKb_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(psbtB64_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, psbtB64_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRecipient());
    }
    if (feeRatePerKb_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, feeRatePerKb_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest other = (com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest) obj;

    if (!getPsbtB64()
        .equals(other.getPsbtB64())) return false;
    if (hasRecipient() != other.hasRecipient()) return false;
    if (hasRecipient()) {
      if (!getRecipient()
          .equals(other.getRecipient())) return false;
    }
    if (getFeeRatePerKb()
        != other.getFeeRatePerKb()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PSBT_B64_FIELD_NUMBER;
    hash = (53 * hash) + getPsbtB64().hashCode();
    if (hasRecipient()) {
      hash = (37 * hash) + RECIPIENT_FIELD_NUMBER;
      hash = (53 * hash) + getRecipient().hashCode();
    }
    hash = (37 * hash) + FEE_RATE_PER_KB_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFeeRatePerKb());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PsbtAddRecipientRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PsbtAddRecipientRequest)
      com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddRecipientRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddRecipientRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest.class, com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRecipientFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      psbtB64_ = "";
      recipient_ = null;
      if (recipientBuilder_ != null) {
        recipientBuilder_.dispose();
        recipientBuilder_ = null;
      }
      feeRatePerKb_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtAddRecipientRequest_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest build() {
      com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest result = new com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.psbtB64_ = psbtB64_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.recipient_ = recipientBuilder_ == null
            ? recipient_
            : recipientBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.feeRatePerKb_ = feeRatePerKb_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest.getDefaultInstance()) return this;
      if (!other.getPsbtB64().isEmpty()) {
        psbtB64_ = other.psbtB64_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasRecipient()) {
        mergeRecipient(other.getRecipient());
      }
      if (other.getFeeRatePerKb() != 0L) {
        setFeeRatePerKb(other.getFeeRatePerKb());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              psbtB64_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetRecipientFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              feeRatePerKb_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object psbtB64_ = "";
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @return The psbtB64.
     */
    public java.lang.String getPsbtB64() {
      java.lang.Object ref = psbtB64_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        psbtB64_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @return The bytes for psbtB64.
     */
    public com.google.protobuf.ByteString
        getPsbtB64Bytes() {
      java.lang.Object ref = psbtB64_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        psbtB64_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @param value The psbtB64 to set.
     * @return This builder for chaining.
     */
    public Builder setPsbtB64(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      psbtB64_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPsbtB64() {
      psbtB64_ = getDefaultInstance().getPsbtB64();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @param value The bytes for psbtB64 to set.
     * @return This builder for chaining.
     */
    public Builder setPsbtB64Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      psbtB64_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient recipient_;
    private com.google.protobuf.SingleFieldBuilder<
        com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder> recipientBuilder_;
    /**
     * <code>.PsbtRecipient recipient = 2;</code>
     * @return Whether the recipient field is set.
     */
    public boolean hasRecipient() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.PsbtRecipient recipient = 2;</code>
     * @return The recipient.
     */
    public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient getRecipient() {
      if (recipientBuilder_ == null) {
        return recipient_ == null ? com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.getDefaultInstance() : recipient_;
      } else {
        return recipientBuilder_.getMessage();
      }
    }
    /**
     * <code>.PsbtRecipient recipient = 2;</code>
     */
    public Builder setRecipient(com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient value) {
      if (recipientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        recipient_ = value;
      } else {
        recipientBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.PsbtRecipient recipient = 2;</code>
     */
    public Builder setRecipient(
        com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder builderForValue) {
      if (recipientBuilder_ == null) {
        recipient_ = builderForValue.build();
      } else {
        recipientBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.PsbtRecipient recipient = 2;</code>
     */
    public Builder mergeRecipient(com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient value) {
      if (recipientBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          recipient_ != null &&
          recipient_ != com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.getDefaultInstance()) {
          getRecipientBuilder().mergeFrom(value);
        } else {
          recipient_ = value;
        }
      } else {
        recipientBuilder_.mergeFrom(value);
      }
      if (recipient_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.PsbtRecipient recipient = 2;</code>
     */
    public Builder clearRecipient() {
      bitField0_ = (bitField0_ & ~0x00000002);
      recipient_ = null;
      if (recipientBuilder_ != null) {
        recipientBuilder_.dispose();
        recipientBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.PsbtRecipient recipient = 2;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder getRecipientBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetRecipientFieldBuilder().getBuilder();
    }
    /**
     * <code>.PsbtRecipient recipient = 2;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder getRecipientOrBuilder() {
      if (recipientBuilder_ != null) {
        return recipientBuilder_.getMessageOrBuilder();
      } else {
        return recipient_ == null ?
            com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.getDefaultInstance() : recipient_;
      }
    }
    /**
     * <code>.PsbtRecipient recipient = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder> 
        internalGetRecipientFieldBuilder() {
      if (recipientBuilder_ == null) {
        recipientBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder>(
                getRecipient(),
                getParentForChildren(),
                isClean());
        recipient_ = null;
      }
      return recipientBuilder_;
    }

    private long feeRatePerKb_ ;
    /**
     * <pre>
     * The fee rate per KB in litoshis.
     * </pre>
     *
     * <code>uint64 fee_rate_per_kb = 3;</code>
     * @return The feeRatePerKb.
     */
    @java.lang.Override
    public long getFeeRatePerKb() {
      return feeRatePerKb_;
    }
    /**
     * <pre>
     * The fee rate per KB in litoshis.
     * </pre>
     *
     * <code>uint64 fee_rate_per_kb = 3;</code>
     * @param value The feeRatePerKb to set.
     * @return This builder for chaining.
     */
    public Builder setFeeRatePerKb(long value) {

      feeRatePerKb_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The fee rate per KB in litoshis.
     * </pre>
     *
     * <code>uint64 fee_rate_per_kb = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFeeRatePerKb() {
      bitField0_ = (bitField0_ & ~0x00000004);
      feeRatePerKb_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PsbtAddRecipientRequest)
  }

  // @@protoc_insertion_point(class_scope:PsbtAddRecipientRequest)
  private static final com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PsbtAddRecipientRequest>
      PARSER = new com.google.protobuf.AbstractParser<PsbtAddRecipientRequest>() {
    @java.lang.Override
    public PsbtAddRecipientRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PsbtAddRecipientRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PsbtAddRecipientRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.PsbtAddRecipientRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

