// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface PsbtGetRecipientsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PsbtGetRecipientsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PsbtRecipient recipient = 1;</code>
   */
  java.util.List<com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient> 
      getRecipientList();
  /**
   * <code>repeated .PsbtRecipient recipient = 1;</code>
   */
  com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient getRecipient(int index);
  /**
   * <code>repeated .PsbtRecipient recipient = 1;</code>
   */
  int getRecipientCount();
  /**
   * <code>repeated .PsbtRecipient recipient = 1;</code>
   */
  java.util.List<? extends com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder> 
      getRecipientOrBuilderList();
  /**
   * <code>repeated .PsbtRecipient recipient = 1;</code>
   */
  com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder getRecipientOrBuilder(
      int index);

  /**
   * <code>repeated string input_address = 2;</code>
   * @return A list containing the inputAddress.
   */
  java.util.List<java.lang.String>
      getInputAddressList();
  /**
   * <code>repeated string input_address = 2;</code>
   * @return The count of inputAddress.
   */
  int getInputAddressCount();
  /**
   * <code>repeated string input_address = 2;</code>
   * @param index The index of the element to return.
   * @return The inputAddress at the given index.
   */
  java.lang.String getInputAddress(int index);
  /**
   * <code>repeated string input_address = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the inputAddress at the given index.
   */
  com.google.protobuf.ByteString
      getInputAddressBytes(int index);

  /**
   * <code>int64 fee = 3;</code>
   * @return The fee.
   */
  long getFee();
}
