// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code PsbtExtractRequest}
 */
@com.google.protobuf.Generated
public final class PsbtExtractRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PsbtExtractRequest)
    PsbtExtractRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "PsbtExtractRequest");
  }
  // Use PsbtExtractRequest.newBuilder() to construct.
  private PsbtExtractRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PsbtExtractRequest() {
    psbtB64_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtExtractRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtExtractRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtExtractRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest.class, com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest.Builder.class);
  }

  public static final int PSBT_B64_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object psbtB64_ = "";
  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The psbtB64.
   */
  @java.lang.Override
  public java.lang.String getPsbtB64() {
    java.lang.Object ref = psbtB64_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      psbtB64_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The PSBT in base64 encoding.
   * </pre>
   *
   * <code>string psbt_b64 = 1;</code>
   * @return The bytes for psbtB64.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPsbtB64Bytes() {
    java.lang.Object ref = psbtB64_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      psbtB64_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNSIGNED_FIELD_NUMBER = 2;
  private boolean unsigned_ = false;
  /**
   * <pre>
   * Extract the unsigned transaction.
   * </pre>
   *
   * <code>bool unsigned = 2;</code>
   * @return The unsigned.
   */
  @java.lang.Override
  public boolean getUnsigned() {
    return unsigned_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(psbtB64_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, psbtB64_);
    }
    if (unsigned_ != false) {
      output.writeBool(2, unsigned_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(psbtB64_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, psbtB64_);
    }
    if (unsigned_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, unsigned_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest other = (com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest) obj;

    if (!getPsbtB64()
        .equals(other.getPsbtB64())) return false;
    if (getUnsigned()
        != other.getUnsigned()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PSBT_B64_FIELD_NUMBER;
    hash = (53 * hash) + getPsbtB64().hashCode();
    hash = (37 * hash) + UNSIGNED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUnsigned());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PsbtExtractRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PsbtExtractRequest)
      com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtExtractRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtExtractRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest.class, com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      psbtB64_ = "";
      unsigned_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtExtractRequest_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest build() {
      com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest result = new com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.psbtB64_ = psbtB64_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.unsigned_ = unsigned_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest.getDefaultInstance()) return this;
      if (!other.getPsbtB64().isEmpty()) {
        psbtB64_ = other.psbtB64_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getUnsigned() != false) {
        setUnsigned(other.getUnsigned());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              psbtB64_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              unsigned_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object psbtB64_ = "";
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @return The psbtB64.
     */
    public java.lang.String getPsbtB64() {
      java.lang.Object ref = psbtB64_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        psbtB64_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @return The bytes for psbtB64.
     */
    public com.google.protobuf.ByteString
        getPsbtB64Bytes() {
      java.lang.Object ref = psbtB64_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        psbtB64_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @param value The psbtB64 to set.
     * @return This builder for chaining.
     */
    public Builder setPsbtB64(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      psbtB64_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPsbtB64() {
      psbtB64_ = getDefaultInstance().getPsbtB64();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The PSBT in base64 encoding.
     * </pre>
     *
     * <code>string psbt_b64 = 1;</code>
     * @param value The bytes for psbtB64 to set.
     * @return This builder for chaining.
     */
    public Builder setPsbtB64Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      psbtB64_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean unsigned_ ;
    /**
     * <pre>
     * Extract the unsigned transaction.
     * </pre>
     *
     * <code>bool unsigned = 2;</code>
     * @return The unsigned.
     */
    @java.lang.Override
    public boolean getUnsigned() {
      return unsigned_;
    }
    /**
     * <pre>
     * Extract the unsigned transaction.
     * </pre>
     *
     * <code>bool unsigned = 2;</code>
     * @param value The unsigned to set.
     * @return This builder for chaining.
     */
    public Builder setUnsigned(boolean value) {

      unsigned_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Extract the unsigned transaction.
     * </pre>
     *
     * <code>bool unsigned = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnsigned() {
      bitField0_ = (bitField0_ & ~0x00000002);
      unsigned_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PsbtExtractRequest)
  }

  // @@protoc_insertion_point(class_scope:PsbtExtractRequest)
  private static final com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PsbtExtractRequest>
      PARSER = new com.google.protobuf.AbstractParser<PsbtExtractRequest>() {
    @java.lang.Override
    public PsbtExtractRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PsbtExtractRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PsbtExtractRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.PsbtExtractRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

