// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code PsbtGetRecipientsResponse}
 */
@com.google.protobuf.Generated
public final class PsbtGetRecipientsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PsbtGetRecipientsResponse)
    PsbtGetRecipientsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "PsbtGetRecipientsResponse");
  }
  // Use PsbtGetRecipientsResponse.newBuilder() to construct.
  private PsbtGetRecipientsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PsbtGetRecipientsResponse() {
    recipient_ = java.util.Collections.emptyList();
    inputAddress_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtGetRecipientsResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtGetRecipientsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtGetRecipientsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse.class, com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse.Builder.class);
  }

  public static final int RECIPIENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient> recipient_;
  /**
   * <code>repeated .PsbtRecipient recipient = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient> getRecipientList() {
    return recipient_;
  }
  /**
   * <code>repeated .PsbtRecipient recipient = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder> 
      getRecipientOrBuilderList() {
    return recipient_;
  }
  /**
   * <code>repeated .PsbtRecipient recipient = 1;</code>
   */
  @java.lang.Override
  public int getRecipientCount() {
    return recipient_.size();
  }
  /**
   * <code>repeated .PsbtRecipient recipient = 1;</code>
   */
  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient getRecipient(int index) {
    return recipient_.get(index);
  }
  /**
   * <code>repeated .PsbtRecipient recipient = 1;</code>
   */
  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder getRecipientOrBuilder(
      int index) {
    return recipient_.get(index);
  }

  public static final int INPUT_ADDRESS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList inputAddress_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string input_address = 2;</code>
   * @return A list containing the inputAddress.
   */
  public com.google.protobuf.ProtocolStringList
      getInputAddressList() {
    return inputAddress_;
  }
  /**
   * <code>repeated string input_address = 2;</code>
   * @return The count of inputAddress.
   */
  public int getInputAddressCount() {
    return inputAddress_.size();
  }
  /**
   * <code>repeated string input_address = 2;</code>
   * @param index The index of the element to return.
   * @return The inputAddress at the given index.
   */
  public java.lang.String getInputAddress(int index) {
    return inputAddress_.get(index);
  }
  /**
   * <code>repeated string input_address = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the inputAddress at the given index.
   */
  public com.google.protobuf.ByteString
      getInputAddressBytes(int index) {
    return inputAddress_.getByteString(index);
  }

  public static final int FEE_FIELD_NUMBER = 3;
  private long fee_ = 0L;
  /**
   * <code>int64 fee = 3;</code>
   * @return The fee.
   */
  @java.lang.Override
  public long getFee() {
    return fee_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < recipient_.size(); i++) {
      output.writeMessage(1, recipient_.get(i));
    }
    for (int i = 0; i < inputAddress_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, inputAddress_.getRaw(i));
    }
    if (fee_ != 0L) {
      output.writeInt64(3, fee_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = recipient_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(recipient_.get(i));
          }
          size += 1 * count;
        }
    {
      int dataSize = 0;
      for (int i = 0; i < inputAddress_.size(); i++) {
        dataSize += computeStringSizeNoTag(inputAddress_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInputAddressList().size();
    }
    if (fee_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, fee_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse other = (com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse) obj;

    if (!getRecipientList()
        .equals(other.getRecipientList())) return false;
    if (!getInputAddressList()
        .equals(other.getInputAddressList())) return false;
    if (getFee()
        != other.getFee()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRecipientCount() > 0) {
      hash = (37 * hash) + RECIPIENT_FIELD_NUMBER;
      hash = (53 * hash) + getRecipientList().hashCode();
    }
    if (getInputAddressCount() > 0) {
      hash = (37 * hash) + INPUT_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getInputAddressList().hashCode();
    }
    hash = (37 * hash) + FEE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFee());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PsbtGetRecipientsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PsbtGetRecipientsResponse)
      com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtGetRecipientsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtGetRecipientsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse.class, com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (recipientBuilder_ == null) {
        recipient_ = java.util.Collections.emptyList();
      } else {
        recipient_ = null;
        recipientBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      inputAddress_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      fee_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_PsbtGetRecipientsResponse_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse build() {
      com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse result = new com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse result) {
      if (recipientBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          recipient_ = java.util.Collections.unmodifiableList(recipient_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.recipient_ = recipient_;
      } else {
        result.recipient_ = recipientBuilder_.build();
      }
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        inputAddress_.makeImmutable();
        result.inputAddress_ = inputAddress_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.fee_ = fee_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse.getDefaultInstance()) return this;
      if (recipientBuilder_ == null) {
        if (!other.recipient_.isEmpty()) {
          if (recipient_.isEmpty()) {
            recipient_ = other.recipient_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecipientIsMutable();
            recipient_.addAll(other.recipient_);
          }
          onChanged();
        }
      } else {
        if (!other.recipient_.isEmpty()) {
          if (recipientBuilder_.isEmpty()) {
            recipientBuilder_.dispose();
            recipientBuilder_ = null;
            recipient_ = other.recipient_;
            bitField0_ = (bitField0_ & ~0x00000001);
            recipientBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetRecipientFieldBuilder() : null;
          } else {
            recipientBuilder_.addAllMessages(other.recipient_);
          }
        }
      }
      if (!other.inputAddress_.isEmpty()) {
        if (inputAddress_.isEmpty()) {
          inputAddress_ = other.inputAddress_;
          bitField0_ |= 0x00000002;
        } else {
          ensureInputAddressIsMutable();
          inputAddress_.addAll(other.inputAddress_);
        }
        onChanged();
      }
      if (other.getFee() != 0L) {
        setFee(other.getFee());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient m =
                  input.readMessage(
                      com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.parser(),
                      extensionRegistry);
              if (recipientBuilder_ == null) {
                ensureRecipientIsMutable();
                recipient_.add(m);
              } else {
                recipientBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              ensureInputAddressIsMutable();
              inputAddress_.add(input.readStringRequireUtf8());
              break;
            } // case 18
            case 24: {
              fee_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient> recipient_ =
      java.util.Collections.emptyList();
    private void ensureRecipientIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        recipient_ = new java.util.ArrayList<com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient>(recipient_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder> recipientBuilder_;

    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public java.util.List<com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient> getRecipientList() {
      if (recipientBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recipient_);
      } else {
        return recipientBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public int getRecipientCount() {
      if (recipientBuilder_ == null) {
        return recipient_.size();
      } else {
        return recipientBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient getRecipient(int index) {
      if (recipientBuilder_ == null) {
        return recipient_.get(index);
      } else {
        return recipientBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public Builder setRecipient(
        int index, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient value) {
      if (recipientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipientIsMutable();
        recipient_.set(index, value);
        onChanged();
      } else {
        recipientBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public Builder setRecipient(
        int index, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder builderForValue) {
      if (recipientBuilder_ == null) {
        ensureRecipientIsMutable();
        recipient_.set(index, builderForValue.build());
        onChanged();
      } else {
        recipientBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public Builder addRecipient(com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient value) {
      if (recipientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipientIsMutable();
        recipient_.add(value);
        onChanged();
      } else {
        recipientBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public Builder addRecipient(
        int index, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient value) {
      if (recipientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipientIsMutable();
        recipient_.add(index, value);
        onChanged();
      } else {
        recipientBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public Builder addRecipient(
        com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder builderForValue) {
      if (recipientBuilder_ == null) {
        ensureRecipientIsMutable();
        recipient_.add(builderForValue.build());
        onChanged();
      } else {
        recipientBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public Builder addRecipient(
        int index, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder builderForValue) {
      if (recipientBuilder_ == null) {
        ensureRecipientIsMutable();
        recipient_.add(index, builderForValue.build());
        onChanged();
      } else {
        recipientBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public Builder addAllRecipient(
        java.lang.Iterable<? extends com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient> values) {
      if (recipientBuilder_ == null) {
        ensureRecipientIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recipient_);
        onChanged();
      } else {
        recipientBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public Builder clearRecipient() {
      if (recipientBuilder_ == null) {
        recipient_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        recipientBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public Builder removeRecipient(int index) {
      if (recipientBuilder_ == null) {
        ensureRecipientIsMutable();
        recipient_.remove(index);
        onChanged();
      } else {
        recipientBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder getRecipientBuilder(
        int index) {
      return internalGetRecipientFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder getRecipientOrBuilder(
        int index) {
      if (recipientBuilder_ == null) {
        return recipient_.get(index);  } else {
        return recipientBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public java.util.List<? extends com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder> 
         getRecipientOrBuilderList() {
      if (recipientBuilder_ != null) {
        return recipientBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recipient_);
      }
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder addRecipientBuilder() {
      return internalGetRecipientFieldBuilder().addBuilder(
          com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.getDefaultInstance());
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder addRecipientBuilder(
        int index) {
      return internalGetRecipientFieldBuilder().addBuilder(
          index, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.getDefaultInstance());
    }
    /**
     * <code>repeated .PsbtRecipient recipient = 1;</code>
     */
    public java.util.List<com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder> 
         getRecipientBuilderList() {
      return internalGetRecipientFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder> 
        internalGetRecipientFieldBuilder() {
      if (recipientBuilder_ == null) {
        recipientBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipient.Builder, com.sparrowwallet.sparrow.mweb.proto.PsbtRecipientOrBuilder>(
                recipient_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        recipient_ = null;
      }
      return recipientBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList inputAddress_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureInputAddressIsMutable() {
      if (!inputAddress_.isModifiable()) {
        inputAddress_ = new com.google.protobuf.LazyStringArrayList(inputAddress_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string input_address = 2;</code>
     * @return A list containing the inputAddress.
     */
    public com.google.protobuf.ProtocolStringList
        getInputAddressList() {
      inputAddress_.makeImmutable();
      return inputAddress_;
    }
    /**
     * <code>repeated string input_address = 2;</code>
     * @return The count of inputAddress.
     */
    public int getInputAddressCount() {
      return inputAddress_.size();
    }
    /**
     * <code>repeated string input_address = 2;</code>
     * @param index The index of the element to return.
     * @return The inputAddress at the given index.
     */
    public java.lang.String getInputAddress(int index) {
      return inputAddress_.get(index);
    }
    /**
     * <code>repeated string input_address = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the inputAddress at the given index.
     */
    public com.google.protobuf.ByteString
        getInputAddressBytes(int index) {
      return inputAddress_.getByteString(index);
    }
    /**
     * <code>repeated string input_address = 2;</code>
     * @param index The index to set the value at.
     * @param value The inputAddress to set.
     * @return This builder for chaining.
     */
    public Builder setInputAddress(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureInputAddressIsMutable();
      inputAddress_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string input_address = 2;</code>
     * @param value The inputAddress to add.
     * @return This builder for chaining.
     */
    public Builder addInputAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureInputAddressIsMutable();
      inputAddress_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string input_address = 2;</code>
     * @param values The inputAddress to add.
     * @return This builder for chaining.
     */
    public Builder addAllInputAddress(
        java.lang.Iterable<java.lang.String> values) {
      ensureInputAddressIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, inputAddress_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string input_address = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInputAddress() {
      inputAddress_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string input_address = 2;</code>
     * @param value The bytes of the inputAddress to add.
     * @return This builder for chaining.
     */
    public Builder addInputAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureInputAddressIsMutable();
      inputAddress_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long fee_ ;
    /**
     * <code>int64 fee = 3;</code>
     * @return The fee.
     */
    @java.lang.Override
    public long getFee() {
      return fee_;
    }
    /**
     * <code>int64 fee = 3;</code>
     * @param value The fee to set.
     * @return This builder for chaining.
     */
    public Builder setFee(long value) {

      fee_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 fee = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFee() {
      bitField0_ = (bitField0_ & ~0x00000004);
      fee_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PsbtGetRecipientsResponse)
  }

  // @@protoc_insertion_point(class_scope:PsbtGetRecipientsResponse)
  private static final com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PsbtGetRecipientsResponse>
      PARSER = new com.google.protobuf.AbstractParser<PsbtGetRecipientsResponse>() {
    @java.lang.Override
    public PsbtGetRecipientsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PsbtGetRecipientsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PsbtGetRecipientsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.PsbtGetRecipientsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

