// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code SpentRequest}
 */
@com.google.protobuf.Generated
public final class SpentRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:SpentRequest)
    SpentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "SpentRequest");
  }
  // Use SpentRequest.newBuilder() to construct.
  private SpentRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SpentRequest() {
    outputId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_SpentRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_SpentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_SpentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.SpentRequest.class, com.sparrowwallet.sparrow.mweb.proto.SpentRequest.Builder.class);
  }

  public static final int OUTPUT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList outputId_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * An array of output IDs to perform checks for.
   * </pre>
   *
   * <code>repeated string output_id = 1;</code>
   * @return A list containing the outputId.
   */
  public com.google.protobuf.ProtocolStringList
      getOutputIdList() {
    return outputId_;
  }
  /**
   * <pre>
   * An array of output IDs to perform checks for.
   * </pre>
   *
   * <code>repeated string output_id = 1;</code>
   * @return The count of outputId.
   */
  public int getOutputIdCount() {
    return outputId_.size();
  }
  /**
   * <pre>
   * An array of output IDs to perform checks for.
   * </pre>
   *
   * <code>repeated string output_id = 1;</code>
   * @param index The index of the element to return.
   * @return The outputId at the given index.
   */
  public java.lang.String getOutputId(int index) {
    return outputId_.get(index);
  }
  /**
   * <pre>
   * An array of output IDs to perform checks for.
   * </pre>
   *
   * <code>repeated string output_id = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the outputId at the given index.
   */
  public com.google.protobuf.ByteString
      getOutputIdBytes(int index) {
    return outputId_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < outputId_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, outputId_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < outputId_.size(); i++) {
        dataSize += computeStringSizeNoTag(outputId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOutputIdList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.SpentRequest)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.SpentRequest other = (com.sparrowwallet.sparrow.mweb.proto.SpentRequest) obj;

    if (!getOutputIdList()
        .equals(other.getOutputIdList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOutputIdCount() > 0) {
      hash = (37 * hash) + OUTPUT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getOutputIdList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.SpentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SpentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SpentRequest)
      com.sparrowwallet.sparrow.mweb.proto.SpentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_SpentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_SpentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.SpentRequest.class, com.sparrowwallet.sparrow.mweb.proto.SpentRequest.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.SpentRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      outputId_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_SpentRequest_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.SpentRequest getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.SpentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.SpentRequest build() {
      com.sparrowwallet.sparrow.mweb.proto.SpentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.SpentRequest buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.SpentRequest result = new com.sparrowwallet.sparrow.mweb.proto.SpentRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.SpentRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        outputId_.makeImmutable();
        result.outputId_ = outputId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.SpentRequest) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.SpentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.SpentRequest other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.SpentRequest.getDefaultInstance()) return this;
      if (!other.outputId_.isEmpty()) {
        if (outputId_.isEmpty()) {
          outputId_ = other.outputId_;
          bitField0_ |= 0x00000001;
        } else {
          ensureOutputIdIsMutable();
          outputId_.addAll(other.outputId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ensureOutputIdIsMutable();
              outputId_.add(input.readStringRequireUtf8());
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList outputId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureOutputIdIsMutable() {
      if (!outputId_.isModifiable()) {
        outputId_ = new com.google.protobuf.LazyStringArrayList(outputId_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * An array of output IDs to perform checks for.
     * </pre>
     *
     * <code>repeated string output_id = 1;</code>
     * @return A list containing the outputId.
     */
    public com.google.protobuf.ProtocolStringList
        getOutputIdList() {
      outputId_.makeImmutable();
      return outputId_;
    }
    /**
     * <pre>
     * An array of output IDs to perform checks for.
     * </pre>
     *
     * <code>repeated string output_id = 1;</code>
     * @return The count of outputId.
     */
    public int getOutputIdCount() {
      return outputId_.size();
    }
    /**
     * <pre>
     * An array of output IDs to perform checks for.
     * </pre>
     *
     * <code>repeated string output_id = 1;</code>
     * @param index The index of the element to return.
     * @return The outputId at the given index.
     */
    public java.lang.String getOutputId(int index) {
      return outputId_.get(index);
    }
    /**
     * <pre>
     * An array of output IDs to perform checks for.
     * </pre>
     *
     * <code>repeated string output_id = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the outputId at the given index.
     */
    public com.google.protobuf.ByteString
        getOutputIdBytes(int index) {
      return outputId_.getByteString(index);
    }
    /**
     * <pre>
     * An array of output IDs to perform checks for.
     * </pre>
     *
     * <code>repeated string output_id = 1;</code>
     * @param index The index to set the value at.
     * @param value The outputId to set.
     * @return This builder for chaining.
     */
    public Builder setOutputId(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOutputIdIsMutable();
      outputId_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An array of output IDs to perform checks for.
     * </pre>
     *
     * <code>repeated string output_id = 1;</code>
     * @param value The outputId to add.
     * @return This builder for chaining.
     */
    public Builder addOutputId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOutputIdIsMutable();
      outputId_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An array of output IDs to perform checks for.
     * </pre>
     *
     * <code>repeated string output_id = 1;</code>
     * @param values The outputId to add.
     * @return This builder for chaining.
     */
    public Builder addAllOutputId(
        java.lang.Iterable<java.lang.String> values) {
      ensureOutputIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, outputId_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An array of output IDs to perform checks for.
     * </pre>
     *
     * <code>repeated string output_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputId() {
      outputId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An array of output IDs to perform checks for.
     * </pre>
     *
     * <code>repeated string output_id = 1;</code>
     * @param value The bytes of the outputId to add.
     * @return This builder for chaining.
     */
    public Builder addOutputIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureOutputIdIsMutable();
      outputId_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SpentRequest)
  }

  // @@protoc_insertion_point(class_scope:SpentRequest)
  private static final com.sparrowwallet.sparrow.mweb.proto.SpentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.SpentRequest();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.SpentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpentRequest>
      PARSER = new com.google.protobuf.AbstractParser<SpentRequest>() {
    @java.lang.Override
    public SpentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SpentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SpentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.SpentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

