// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StatusRequest)
    com.google.protobuf.MessageOrBuilder {
}
