// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The height of the latest block.
   * </pre>
   *
   * <code>int32 block_header_height = 1;</code>
   * @return The blockHeaderHeight.
   */
  int getBlockHeaderHeight();

  /**
   * <pre>
   * The height of the latest MWEB header.
   * </pre>
   *
   * <code>int32 mweb_header_height = 2;</code>
   * @return The mwebHeaderHeight.
   */
  int getMwebHeaderHeight();

  /**
   * <pre>
   * The height at which the MWEB utxo set is synced to.
   * </pre>
   *
   * <code>int32 mweb_utxos_height = 3;</code>
   * @return The mwebUtxosHeight.
   */
  int getMwebUtxosHeight();

  /**
   * <pre>
   * The timestamp of the latest block.
   * </pre>
   *
   * <code>uint32 block_time = 4;</code>
   * @return The blockTime.
   */
  int getBlockTime();
}
