// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code StatusResponse}
 */
@com.google.protobuf.Generated
public final class StatusResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:StatusResponse)
    StatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "StatusResponse");
  }
  // Use StatusResponse.newBuilder() to construct.
  private StatusResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StatusResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_StatusResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_StatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_StatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.StatusResponse.class, com.sparrowwallet.sparrow.mweb.proto.StatusResponse.Builder.class);
  }

  public static final int BLOCK_HEADER_HEIGHT_FIELD_NUMBER = 1;
  private int blockHeaderHeight_ = 0;
  /**
   * <pre>
   * The height of the latest block.
   * </pre>
   *
   * <code>int32 block_header_height = 1;</code>
   * @return The blockHeaderHeight.
   */
  @java.lang.Override
  public int getBlockHeaderHeight() {
    return blockHeaderHeight_;
  }

  public static final int MWEB_HEADER_HEIGHT_FIELD_NUMBER = 2;
  private int mwebHeaderHeight_ = 0;
  /**
   * <pre>
   * The height of the latest MWEB header.
   * </pre>
   *
   * <code>int32 mweb_header_height = 2;</code>
   * @return The mwebHeaderHeight.
   */
  @java.lang.Override
  public int getMwebHeaderHeight() {
    return mwebHeaderHeight_;
  }

  public static final int MWEB_UTXOS_HEIGHT_FIELD_NUMBER = 3;
  private int mwebUtxosHeight_ = 0;
  /**
   * <pre>
   * The height at which the MWEB utxo set is synced to.
   * </pre>
   *
   * <code>int32 mweb_utxos_height = 3;</code>
   * @return The mwebUtxosHeight.
   */
  @java.lang.Override
  public int getMwebUtxosHeight() {
    return mwebUtxosHeight_;
  }

  public static final int BLOCK_TIME_FIELD_NUMBER = 4;
  private int blockTime_ = 0;
  /**
   * <pre>
   * The timestamp of the latest block.
   * </pre>
   *
   * <code>uint32 block_time = 4;</code>
   * @return The blockTime.
   */
  @java.lang.Override
  public int getBlockTime() {
    return blockTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (blockHeaderHeight_ != 0) {
      output.writeInt32(1, blockHeaderHeight_);
    }
    if (mwebHeaderHeight_ != 0) {
      output.writeInt32(2, mwebHeaderHeight_);
    }
    if (mwebUtxosHeight_ != 0) {
      output.writeInt32(3, mwebUtxosHeight_);
    }
    if (blockTime_ != 0) {
      output.writeUInt32(4, blockTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (blockHeaderHeight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, blockHeaderHeight_);
    }
    if (mwebHeaderHeight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, mwebHeaderHeight_);
    }
    if (mwebUtxosHeight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, mwebUtxosHeight_);
    }
    if (blockTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, blockTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.StatusResponse)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.StatusResponse other = (com.sparrowwallet.sparrow.mweb.proto.StatusResponse) obj;

    if (getBlockHeaderHeight()
        != other.getBlockHeaderHeight()) return false;
    if (getMwebHeaderHeight()
        != other.getMwebHeaderHeight()) return false;
    if (getMwebUtxosHeight()
        != other.getMwebUtxosHeight()) return false;
    if (getBlockTime()
        != other.getBlockTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOCK_HEADER_HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getBlockHeaderHeight();
    hash = (37 * hash) + MWEB_HEADER_HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getMwebHeaderHeight();
    hash = (37 * hash) + MWEB_UTXOS_HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getMwebUtxosHeight();
    hash = (37 * hash) + BLOCK_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getBlockTime();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.StatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code StatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StatusResponse)
      com.sparrowwallet.sparrow.mweb.proto.StatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_StatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_StatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.StatusResponse.class, com.sparrowwallet.sparrow.mweb.proto.StatusResponse.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.StatusResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      blockHeaderHeight_ = 0;
      mwebHeaderHeight_ = 0;
      mwebUtxosHeight_ = 0;
      blockTime_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_StatusResponse_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.StatusResponse getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.StatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.StatusResponse build() {
      com.sparrowwallet.sparrow.mweb.proto.StatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.StatusResponse buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.StatusResponse result = new com.sparrowwallet.sparrow.mweb.proto.StatusResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.StatusResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.blockHeaderHeight_ = blockHeaderHeight_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.mwebHeaderHeight_ = mwebHeaderHeight_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.mwebUtxosHeight_ = mwebUtxosHeight_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.blockTime_ = blockTime_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.StatusResponse) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.StatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.StatusResponse other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.StatusResponse.getDefaultInstance()) return this;
      if (other.getBlockHeaderHeight() != 0) {
        setBlockHeaderHeight(other.getBlockHeaderHeight());
      }
      if (other.getMwebHeaderHeight() != 0) {
        setMwebHeaderHeight(other.getMwebHeaderHeight());
      }
      if (other.getMwebUtxosHeight() != 0) {
        setMwebUtxosHeight(other.getMwebUtxosHeight());
      }
      if (other.getBlockTime() != 0) {
        setBlockTime(other.getBlockTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              blockHeaderHeight_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              mwebHeaderHeight_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              mwebUtxosHeight_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              blockTime_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int blockHeaderHeight_ ;
    /**
     * <pre>
     * The height of the latest block.
     * </pre>
     *
     * <code>int32 block_header_height = 1;</code>
     * @return The blockHeaderHeight.
     */
    @java.lang.Override
    public int getBlockHeaderHeight() {
      return blockHeaderHeight_;
    }
    /**
     * <pre>
     * The height of the latest block.
     * </pre>
     *
     * <code>int32 block_header_height = 1;</code>
     * @param value The blockHeaderHeight to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHeaderHeight(int value) {

      blockHeaderHeight_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The height of the latest block.
     * </pre>
     *
     * <code>int32 block_header_height = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockHeaderHeight() {
      bitField0_ = (bitField0_ & ~0x00000001);
      blockHeaderHeight_ = 0;
      onChanged();
      return this;
    }

    private int mwebHeaderHeight_ ;
    /**
     * <pre>
     * The height of the latest MWEB header.
     * </pre>
     *
     * <code>int32 mweb_header_height = 2;</code>
     * @return The mwebHeaderHeight.
     */
    @java.lang.Override
    public int getMwebHeaderHeight() {
      return mwebHeaderHeight_;
    }
    /**
     * <pre>
     * The height of the latest MWEB header.
     * </pre>
     *
     * <code>int32 mweb_header_height = 2;</code>
     * @param value The mwebHeaderHeight to set.
     * @return This builder for chaining.
     */
    public Builder setMwebHeaderHeight(int value) {

      mwebHeaderHeight_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The height of the latest MWEB header.
     * </pre>
     *
     * <code>int32 mweb_header_height = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMwebHeaderHeight() {
      bitField0_ = (bitField0_ & ~0x00000002);
      mwebHeaderHeight_ = 0;
      onChanged();
      return this;
    }

    private int mwebUtxosHeight_ ;
    /**
     * <pre>
     * The height at which the MWEB utxo set is synced to.
     * </pre>
     *
     * <code>int32 mweb_utxos_height = 3;</code>
     * @return The mwebUtxosHeight.
     */
    @java.lang.Override
    public int getMwebUtxosHeight() {
      return mwebUtxosHeight_;
    }
    /**
     * <pre>
     * The height at which the MWEB utxo set is synced to.
     * </pre>
     *
     * <code>int32 mweb_utxos_height = 3;</code>
     * @param value The mwebUtxosHeight to set.
     * @return This builder for chaining.
     */
    public Builder setMwebUtxosHeight(int value) {

      mwebUtxosHeight_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The height at which the MWEB utxo set is synced to.
     * </pre>
     *
     * <code>int32 mweb_utxos_height = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMwebUtxosHeight() {
      bitField0_ = (bitField0_ & ~0x00000004);
      mwebUtxosHeight_ = 0;
      onChanged();
      return this;
    }

    private int blockTime_ ;
    /**
     * <pre>
     * The timestamp of the latest block.
     * </pre>
     *
     * <code>uint32 block_time = 4;</code>
     * @return The blockTime.
     */
    @java.lang.Override
    public int getBlockTime() {
      return blockTime_;
    }
    /**
     * <pre>
     * The timestamp of the latest block.
     * </pre>
     *
     * <code>uint32 block_time = 4;</code>
     * @param value The blockTime to set.
     * @return This builder for chaining.
     */
    public Builder setBlockTime(int value) {

      blockTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The timestamp of the latest block.
     * </pre>
     *
     * <code>uint32 block_time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      blockTime_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:StatusResponse)
  }

  // @@protoc_insertion_point(class_scope:StatusResponse)
  private static final com.sparrowwallet.sparrow.mweb.proto.StatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.StatusResponse();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.StatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<StatusResponse>() {
    @java.lang.Override
    public StatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.StatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

