// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code UtxosRequest}
 */
@com.google.protobuf.Generated
public final class UtxosRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:UtxosRequest)
    UtxosRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "UtxosRequest");
  }
  // Use UtxosRequest.newBuilder() to construct.
  private UtxosRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UtxosRequest() {
    scanSecret_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_UtxosRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_UtxosRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_UtxosRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.UtxosRequest.class, com.sparrowwallet.sparrow.mweb.proto.UtxosRequest.Builder.class);
  }

  public static final int FROM_HEIGHT_FIELD_NUMBER = 1;
  private int fromHeight_ = 0;
  /**
   * <pre>
   * The block height from which to start fetching utxos from.
   * After all mined utxos have been streamed, unconfirmed and
   * newly confirmed utxos will also be streamed. If this is set
   * to 0 then all utxos belonging to the account will be fetched.
   * </pre>
   *
   * <code>int32 from_height = 1;</code>
   * @return The fromHeight.
   */
  @java.lang.Override
  public int getFromHeight() {
    return fromHeight_;
  }

  public static final int SCAN_SECRET_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString scanSecret_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * The scan secret or view key represents the account for
   * which utxos should be streamed.
   * </pre>
   *
   * <code>bytes scan_secret = 2;</code>
   * @return The scanSecret.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getScanSecret() {
    return scanSecret_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fromHeight_ != 0) {
      output.writeInt32(1, fromHeight_);
    }
    if (!scanSecret_.isEmpty()) {
      output.writeBytes(2, scanSecret_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fromHeight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, fromHeight_);
    }
    if (!scanSecret_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, scanSecret_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.UtxosRequest)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.UtxosRequest other = (com.sparrowwallet.sparrow.mweb.proto.UtxosRequest) obj;

    if (getFromHeight()
        != other.getFromHeight()) return false;
    if (!getScanSecret()
        .equals(other.getScanSecret())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROM_HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getFromHeight();
    hash = (37 * hash) + SCAN_SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getScanSecret().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.UtxosRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UtxosRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UtxosRequest)
      com.sparrowwallet.sparrow.mweb.proto.UtxosRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_UtxosRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_UtxosRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.UtxosRequest.class, com.sparrowwallet.sparrow.mweb.proto.UtxosRequest.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.UtxosRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fromHeight_ = 0;
      scanSecret_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_UtxosRequest_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.UtxosRequest getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.UtxosRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.UtxosRequest build() {
      com.sparrowwallet.sparrow.mweb.proto.UtxosRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.UtxosRequest buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.UtxosRequest result = new com.sparrowwallet.sparrow.mweb.proto.UtxosRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.UtxosRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fromHeight_ = fromHeight_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.scanSecret_ = scanSecret_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.UtxosRequest) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.UtxosRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.UtxosRequest other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.UtxosRequest.getDefaultInstance()) return this;
      if (other.getFromHeight() != 0) {
        setFromHeight(other.getFromHeight());
      }
      if (!other.getScanSecret().isEmpty()) {
        setScanSecret(other.getScanSecret());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              fromHeight_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              scanSecret_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int fromHeight_ ;
    /**
     * <pre>
     * The block height from which to start fetching utxos from.
     * After all mined utxos have been streamed, unconfirmed and
     * newly confirmed utxos will also be streamed. If this is set
     * to 0 then all utxos belonging to the account will be fetched.
     * </pre>
     *
     * <code>int32 from_height = 1;</code>
     * @return The fromHeight.
     */
    @java.lang.Override
    public int getFromHeight() {
      return fromHeight_;
    }
    /**
     * <pre>
     * The block height from which to start fetching utxos from.
     * After all mined utxos have been streamed, unconfirmed and
     * newly confirmed utxos will also be streamed. If this is set
     * to 0 then all utxos belonging to the account will be fetched.
     * </pre>
     *
     * <code>int32 from_height = 1;</code>
     * @param value The fromHeight to set.
     * @return This builder for chaining.
     */
    public Builder setFromHeight(int value) {

      fromHeight_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The block height from which to start fetching utxos from.
     * After all mined utxos have been streamed, unconfirmed and
     * newly confirmed utxos will also be streamed. If this is set
     * to 0 then all utxos belonging to the account will be fetched.
     * </pre>
     *
     * <code>int32 from_height = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromHeight() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fromHeight_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString scanSecret_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The scan secret or view key represents the account for
     * which utxos should be streamed.
     * </pre>
     *
     * <code>bytes scan_secret = 2;</code>
     * @return The scanSecret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getScanSecret() {
      return scanSecret_;
    }
    /**
     * <pre>
     * The scan secret or view key represents the account for
     * which utxos should be streamed.
     * </pre>
     *
     * <code>bytes scan_secret = 2;</code>
     * @param value The scanSecret to set.
     * @return This builder for chaining.
     */
    public Builder setScanSecret(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      scanSecret_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The scan secret or view key represents the account for
     * which utxos should be streamed.
     * </pre>
     *
     * <code>bytes scan_secret = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearScanSecret() {
      bitField0_ = (bitField0_ & ~0x00000002);
      scanSecret_ = getDefaultInstance().getScanSecret();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:UtxosRequest)
  }

  // @@protoc_insertion_point(class_scope:UtxosRequest)
  private static final com.sparrowwallet.sparrow.mweb.proto.UtxosRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.UtxosRequest();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.UtxosRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UtxosRequest>
      PARSER = new com.google.protobuf.AbstractParser<UtxosRequest>() {
    @java.lang.Override
    public UtxosRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UtxosRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UtxosRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.UtxosRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

