// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

/**
 * Protobuf type {@code Utxo}
 */
@com.google.protobuf.Generated
public final class Utxo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Utxo)
    UtxoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "Utxo");
  }
  // Use Utxo.newBuilder() to construct.
  private Utxo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Utxo() {
    address_ = "";
    outputId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_Utxo_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_Utxo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_Utxo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sparrowwallet.sparrow.mweb.proto.Utxo.class, com.sparrowwallet.sparrow.mweb.proto.Utxo.Builder.class);
  }

  public static final int HEIGHT_FIELD_NUMBER = 1;
  private int height_ = 0;
  /**
   * <pre>
   * The block height of the utxo, or 0 for unconfirmed.
   * </pre>
   *
   * <code>int32 height = 1;</code>
   * @return The height.
   */
  @java.lang.Override
  public int getHeight() {
    return height_;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private long value_ = 0L;
  /**
   * <pre>
   * The value of the utxo in litoshis.
   * </pre>
   *
   * <code>uint64 value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public long getValue() {
    return value_;
  }

  public static final int ADDRESS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object address_ = "";
  /**
   * <pre>
   * The MWEB address that the utxo was received on.
   * </pre>
   *
   * <code>string address = 3;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The MWEB address that the utxo was received on.
   * </pre>
   *
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OUTPUT_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object outputId_ = "";
  /**
   * <pre>
   * The output ID. This functions like a transaction hash,
   * but is unique to every utxo.
   * </pre>
   *
   * <code>string output_id = 4;</code>
   * @return The outputId.
   */
  @java.lang.Override
  public java.lang.String getOutputId() {
    java.lang.Object ref = outputId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outputId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The output ID. This functions like a transaction hash,
   * but is unique to every utxo.
   * </pre>
   *
   * <code>string output_id = 4;</code>
   * @return The bytes for outputId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutputIdBytes() {
    java.lang.Object ref = outputId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outputId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLOCK_TIME_FIELD_NUMBER = 5;
  private int blockTime_ = 0;
  /**
   * <pre>
   * The timestamp of the block the utxo was mined in.
   * </pre>
   *
   * <code>uint32 block_time = 5;</code>
   * @return The blockTime.
   */
  @java.lang.Override
  public int getBlockTime() {
    return blockTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (height_ != 0) {
      output.writeInt32(1, height_);
    }
    if (value_ != 0L) {
      output.writeUInt64(2, value_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, address_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, outputId_);
    }
    if (blockTime_ != 0) {
      output.writeUInt32(5, blockTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (height_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, height_);
    }
    if (value_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, value_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, address_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, outputId_);
    }
    if (blockTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, blockTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sparrowwallet.sparrow.mweb.proto.Utxo)) {
      return super.equals(obj);
    }
    com.sparrowwallet.sparrow.mweb.proto.Utxo other = (com.sparrowwallet.sparrow.mweb.proto.Utxo) obj;

    if (getHeight()
        != other.getHeight()) return false;
    if (getValue()
        != other.getValue()) return false;
    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (!getOutputId()
        .equals(other.getOutputId())) return false;
    if (getBlockTime()
        != other.getBlockTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getHeight();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValue());
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + OUTPUT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOutputId().hashCode();
    hash = (37 * hash) + BLOCK_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getBlockTime();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sparrowwallet.sparrow.mweb.proto.Utxo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sparrowwallet.sparrow.mweb.proto.Utxo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Utxo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Utxo)
      com.sparrowwallet.sparrow.mweb.proto.UtxoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_Utxo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_Utxo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparrowwallet.sparrow.mweb.proto.Utxo.class, com.sparrowwallet.sparrow.mweb.proto.Utxo.Builder.class);
    }

    // Construct using com.sparrowwallet.sparrow.mweb.proto.Utxo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      height_ = 0;
      value_ = 0L;
      address_ = "";
      outputId_ = "";
      blockTime_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Mwebd.internal_static_Utxo_descriptor;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.Utxo getDefaultInstanceForType() {
      return com.sparrowwallet.sparrow.mweb.proto.Utxo.getDefaultInstance();
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.Utxo build() {
      com.sparrowwallet.sparrow.mweb.proto.Utxo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sparrowwallet.sparrow.mweb.proto.Utxo buildPartial() {
      com.sparrowwallet.sparrow.mweb.proto.Utxo result = new com.sparrowwallet.sparrow.mweb.proto.Utxo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sparrowwallet.sparrow.mweb.proto.Utxo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.height_ = height_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.value_ = value_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.address_ = address_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.outputId_ = outputId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.blockTime_ = blockTime_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sparrowwallet.sparrow.mweb.proto.Utxo) {
        return mergeFrom((com.sparrowwallet.sparrow.mweb.proto.Utxo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sparrowwallet.sparrow.mweb.proto.Utxo other) {
      if (other == com.sparrowwallet.sparrow.mweb.proto.Utxo.getDefaultInstance()) return this;
      if (other.getHeight() != 0) {
        setHeight(other.getHeight());
      }
      if (other.getValue() != 0L) {
        setValue(other.getValue());
      }
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getOutputId().isEmpty()) {
        outputId_ = other.outputId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getBlockTime() != 0) {
        setBlockTime(other.getBlockTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              height_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              value_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              address_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              outputId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              blockTime_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int height_ ;
    /**
     * <pre>
     * The block height of the utxo, or 0 for unconfirmed.
     * </pre>
     *
     * <code>int32 height = 1;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }
    /**
     * <pre>
     * The block height of the utxo, or 0 for unconfirmed.
     * </pre>
     *
     * <code>int32 height = 1;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(int value) {

      height_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The block height of the utxo, or 0 for unconfirmed.
     * </pre>
     *
     * <code>int32 height = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000001);
      height_ = 0;
      onChanged();
      return this;
    }

    private long value_ ;
    /**
     * <pre>
     * The value of the utxo in litoshis.
     * </pre>
     *
     * <code>uint64 value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public long getValue() {
      return value_;
    }
    /**
     * <pre>
     * The value of the utxo in litoshis.
     * </pre>
     *
     * <code>uint64 value = 2;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(long value) {

      value_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The value of the utxo in litoshis.
     * </pre>
     *
     * <code>uint64 value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <pre>
     * The MWEB address that the utxo was received on.
     * </pre>
     *
     * <code>string address = 3;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The MWEB address that the utxo was received on.
     * </pre>
     *
     * <code>string address = 3;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The MWEB address that the utxo was received on.
     * </pre>
     *
     * <code>string address = 3;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      address_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The MWEB address that the utxo was received on.
     * </pre>
     *
     * <code>string address = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      address_ = getDefaultInstance().getAddress();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The MWEB address that the utxo was received on.
     * </pre>
     *
     * <code>string address = 3;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      address_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object outputId_ = "";
    /**
     * <pre>
     * The output ID. This functions like a transaction hash,
     * but is unique to every utxo.
     * </pre>
     *
     * <code>string output_id = 4;</code>
     * @return The outputId.
     */
    public java.lang.String getOutputId() {
      java.lang.Object ref = outputId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The output ID. This functions like a transaction hash,
     * but is unique to every utxo.
     * </pre>
     *
     * <code>string output_id = 4;</code>
     * @return The bytes for outputId.
     */
    public com.google.protobuf.ByteString
        getOutputIdBytes() {
      java.lang.Object ref = outputId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The output ID. This functions like a transaction hash,
     * but is unique to every utxo.
     * </pre>
     *
     * <code>string output_id = 4;</code>
     * @param value The outputId to set.
     * @return This builder for chaining.
     */
    public Builder setOutputId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      outputId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output ID. This functions like a transaction hash,
     * but is unique to every utxo.
     * </pre>
     *
     * <code>string output_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputId() {
      outputId_ = getDefaultInstance().getOutputId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output ID. This functions like a transaction hash,
     * but is unique to every utxo.
     * </pre>
     *
     * <code>string output_id = 4;</code>
     * @param value The bytes for outputId to set.
     * @return This builder for chaining.
     */
    public Builder setOutputIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      outputId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int blockTime_ ;
    /**
     * <pre>
     * The timestamp of the block the utxo was mined in.
     * </pre>
     *
     * <code>uint32 block_time = 5;</code>
     * @return The blockTime.
     */
    @java.lang.Override
    public int getBlockTime() {
      return blockTime_;
    }
    /**
     * <pre>
     * The timestamp of the block the utxo was mined in.
     * </pre>
     *
     * <code>uint32 block_time = 5;</code>
     * @param value The blockTime to set.
     * @return This builder for chaining.
     */
    public Builder setBlockTime(int value) {

      blockTime_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The timestamp of the block the utxo was mined in.
     * </pre>
     *
     * <code>uint32 block_time = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockTime() {
      bitField0_ = (bitField0_ & ~0x00000010);
      blockTime_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Utxo)
  }

  // @@protoc_insertion_point(class_scope:Utxo)
  private static final com.sparrowwallet.sparrow.mweb.proto.Utxo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sparrowwallet.sparrow.mweb.proto.Utxo();
  }

  public static com.sparrowwallet.sparrow.mweb.proto.Utxo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Utxo>
      PARSER = new com.google.protobuf.AbstractParser<Utxo>() {
    @java.lang.Override
    public Utxo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Utxo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Utxo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sparrowwallet.sparrow.mweb.proto.Utxo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

