// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mwebd.proto
// Protobuf Java Version: 4.34.0

package com.sparrowwallet.sparrow.mweb.proto;

@com.google.protobuf.Generated
public interface UtxoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Utxo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The block height of the utxo, or 0 for unconfirmed.
   * </pre>
   *
   * <code>int32 height = 1;</code>
   * @return The height.
   */
  int getHeight();

  /**
   * <pre>
   * The value of the utxo in litoshis.
   * </pre>
   *
   * <code>uint64 value = 2;</code>
   * @return The value.
   */
  long getValue();

  /**
   * <pre>
   * The MWEB address that the utxo was received on.
   * </pre>
   *
   * <code>string address = 3;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <pre>
   * The MWEB address that the utxo was received on.
   * </pre>
   *
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <pre>
   * The output ID. This functions like a transaction hash,
   * but is unique to every utxo.
   * </pre>
   *
   * <code>string output_id = 4;</code>
   * @return The outputId.
   */
  java.lang.String getOutputId();
  /**
   * <pre>
   * The output ID. This functions like a transaction hash,
   * but is unique to every utxo.
   * </pre>
   *
   * <code>string output_id = 4;</code>
   * @return The bytes for outputId.
   */
  com.google.protobuf.ByteString
      getOutputIdBytes();

  /**
   * <pre>
   * The timestamp of the block the utxo was mined in.
   * </pre>
   *
   * <code>uint32 block_time = 5;</code>
   * @return The blockTime.
   */
  int getBlockTime();
}
